import type { PhotoKey } from "./photos";

/**
 * THE JOURNEY, DAY BY DAY
 * -----------------------
 * A realistic 15-day expedition itinerary — the practical companion to the
 * cinematic first act. Timings and distances are honest working estimates
 * (verify exact figures and book ahead in Phase Two). Charging is planned
 * around meals, views, and lodgings — never presented as a problem.
 */

export interface MapPoint {
  label: string;
  lat: number;
  lon: number;
  /** Draw the leg reaching this point as a dashed ferry crossing. */
  ferry?: boolean;
}

export interface Stop {
  name: string;
  /** Estimated time at the stop, e.g. "2 hr". */
  time?: string;
  note: string;
  ferry?: boolean;
}

export interface Day {
  n: string;
  region: string;
  leg: string;
  title: string;
  subtitle: string;
  photo?: PhotoKey;
  wake: string;
  breakfast: string;
  drive: string;
  stops: Stop[];
  lunch: string;
  afternoon: string;
  hotel: string;
  dinner: string;
  evening: string;
  charging: string;
  walking: string;
  rainy: string;
  wildlife: string;
  memory: string;
  map: MapPoint[];
}

export const DAYS: Day[] = [
  {
    n: "01",
    region: "The mainland approach",
    leg: "Hudson Valley → Camden, Maine",
    title: "Salt air, by afternoon",
    subtitle: "The house asleep behind you; the coast of Maine ahead by dinner.",
    wake: "Home, Hudson Valley, New York — early, in the dark.",
    breakfast: "Coffee and something quick from the kitchen. You'll eat properly on the road.",
    drive: "≈ 6 hr 30 min · 605 km — I-90 east, then up US-1 along the coast.",
    stops: [
      { name: "Portsmouth, New Hampshire", time: "45 min", note: "A stretch and a harbour walk where New England first smells like the sea." },
      { name: "Portland, Maine", time: "1 hr 30 min", note: "The Old Port — cobblestones, chandleries, the first proper lobster of the trip." },
    ],
    lunch: "[Eventide Oyster Co.](https://www.eventideoysterco.com/), Portland — a brown-butter lobster bun and a dozen cold local oysters.",
    afternoon: "Follow US-1 up the mid-coast, the road threading between spruce and inlet.",
    hotel: "[Camden Harbour Inn](https://www.camdenharbourinn.com/), Camden — a Relais & Châteaux perch above the schooner harbour.",
    dinner: "Natalie's at the inn, or a paper-tray lobster at a working pound if you'd rather keep it plain.",
    evening: "A slow walk to the Camden waterfront; masts ticking, the smell of low tide.",
    charging: "Supercharge in Portland over lunch; a short top-up in Augusta if you like. Level 2 at the inn overnight.",
    walking: "Easy — town strolls only.",
    rainy: "[Farnsworth Art Museum](https://www.farnsworthmuseum.org/) in Rockland (the Wyeths), or simply linger longer over the oysters.",
    wildlife: "Harbour seals hauled out in Camden harbour; ospreys working the masts.",
    memory: "The first lobster roll of the trip, eaten outdoors with the Atlantic finally in the frame.",
    map: [
      { label: "Hudson Valley", lat: 41.7, lon: -73.92 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Camden", lat: 44.21, lon: -69.06 },
    ],
  },
  {
    n: "02",
    region: "The mainland approach",
    leg: "Camden, Maine → Bay of Fundy, New Brunswick",
    title: "The floor of the ocean",
    subtitle: "Across the border to the highest tides on earth.",
    wake: "[Camden Harbour Inn](https://www.camdenharbourinn.com/), above the harbour.",
    breakfast: "A full breakfast at the inn before the border.",
    drive: "≈ 5 hr 30 min · 430 km — US-1 to the Calais crossing, then coastal New Brunswick.",
    stops: [
      { name: "St. Andrews by-the-Sea, NB", time: "1 hr 30 min", note: "A genteel seaside town for lunch; whales sometimes in the bay off the wharf." },
      { name: "[Hopewell Rocks](https://www.thehopewellrocks.ca/)", time: "1 hr 30 min", note: "Walk the actual sea floor at low tide, beneath flowerpot stacks carved by 40 vertical feet of tide." },
    ],
    lunch: "The Niger Reef Tea House or [Rossmount Inn](https://www.rossmountinn.com/), St. Andrews.",
    afternoon: "Time Hopewell for low tide — then watch the Bay of Fundy come back in.",
    hotel: "A Fundy-shore inn near Hopewell, or into Moncton for the night.",
    dinner: "Fundy seafood — scallops and a local ale.",
    evening: "Return to the flats at dusk to see the water swallow the ground you walked at noon.",
    charging: "Supercharge at the border town (St. Stephen) and again in Moncton — both easy, both near food.",
    walking: "Easy–moderate — stairs down to the ocean floor at Hopewell.",
    rainy: "[Kingsbrae Garden](https://www.kingsbraegarden.com/)'s pavilions; the Hopewell interpretive centre. The tide performs in any weather.",
    wildlife: "Shorebirds by the tens of thousands in late summer; peregrines over the cliffs; whales off St. Andrews.",
    memory: "Standing on the ocean floor at Hopewell, then watching four storeys of tide erase it.",
    map: [
      { label: "Camden", lat: 44.21, lon: -69.06 },
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
      { label: "Hopewell Rocks", lat: 45.82, lon: -64.58 },
      { label: "Moncton", lat: 46.09, lon: -64.77 },
    ],
  },
  {
    n: "03",
    region: "The crossing",
    leg: "New Brunswick → North Sydney → overnight ferry",
    title: "The mainland lets go",
    subtitle: "Cape Breton at your back, an island somewhere ahead in the dark.",
    photo: "ferry",
    wake: "New Brunswick — a relaxed start; the ferry is an evening affair.",
    breakfast: "On the road; a diner breakfast somewhere along the Trans-Canada.",
    drive: "≈ 5 hr · 460 km to North Sydney, then the ferry.",
    stops: [
      { name: "Canso Causeway", time: "20 min", note: "Cross onto Cape Breton Island; the first true taste of Atlantic Canada's edge." },
      { name: "[Marine Atlantic](https://www.marineatlantic.ca/) terminal, North Sydney", time: "boarding", note: "The MV Blue Puttees or Highlanders — your cabin for the night crossing to Port aux Basques." },
    ],
    lunch: "A roadside chowder near Antigonish or the causeway.",
    afternoon: "Save the Cabot Trail as the drive you skip on purpose — Newfoundland is the bigger story.",
    hotel: "A cabin aboard the [Marine Atlantic](https://www.marineatlantic.ca/) ferry — dinner, a berth, and the sway of the Cabot Strait.",
    dinner: "Aboard, as the harbour lights of North Sydney slide astern.",
    evening: "The deck after dark. More stars than the whole drive allowed.",
    charging: "Charge to 100% in North Sydney before boarding — the ferry has no charging, and Newfoundland's network begins at Port aux Basques.",
    walking: "Easy.",
    rainy: "Immaterial — you're aboard a ship by evening.",
    wildlife: "Gannets and gulls escorting the ferry out; a possible whale spout at dusk in the Strait.",
    memory: "Standing at the rail near midnight, the mainland gone, nothing ahead but dark water and the idea of an island.",
    map: [
      { label: "Moncton", lat: 46.09, lon: -64.77 },
      { label: "North Sydney", lat: 46.21, lon: -60.25 },
      { label: "Port aux Basques", lat: 47.57, lon: -59.14, ferry: true },
    ],
  },
  {
    n: "04",
    region: "Gros Morne",
    leg: "Port aux Basques → Gros Morne · the Tablelands",
    title: "The planet's guts, in daylight",
    subtitle: "Landfall at first light, and rock that belongs twenty miles underground.",
    photo: "tablelands",
    wake: "A cabin at sea, arriving at first light into Port aux Basques.",
    breakfast: "Aboard, as the coast of Newfoundland resolves out of the mist.",
    drive: "≈ 3 hr north on Route 1, then Route 431 into the park.",
    stops: [
      { name: "Port aux Basques harbour", time: "30 min", note: "First steps on the island; a coffee and the smell of a working fishing town." },
      { name: "The Tablelands, [Gros Morne](https://parks.canada.ca/pn-np/nl/grosmorne)", time: "2 hr", note: "Rust-orange peridotite — the Earth's mantle, exposed and warm in the sun. The Tablelands Trail is flat gravel." },
    ],
    lunch: "[Java Jack's](https://www.javajacks.ca/), Rocky Harbour — local, unfussy, very good.",
    afternoon: "Walk the Tablelands, then drift into Bonne Bay as the light softens.",
    hotel: "Neddies Harbour Inn, Norris Point — quiet rooms over the fjord.",
    dinner: "The Chanterelles restaurant at the inn, or Fisherman's Landing in Rocky Harbour.",
    evening: "Sunset over Bonne Bay from the deck; the fjord walls going pink, then blue.",
    charging: "Fast-charge in Corner Brook on the way north (over a coffee); Level 2 at the inn overnight.",
    walking: "Easy — the Tablelands Trail is flat, 4 km round trip.",
    rainy: "The Gros Morne Discovery Centre at Woody Point explains the geology beautifully; the Trout River loop is scenic in cloud.",
    wildlife: "Moose at dusk (drive carefully — this is moose country), arctic hare, rock ptarmigan on the barrens.",
    memory: "Standing on bare orange mantle rock that belongs deep inside the planet, warm underfoot in the afternoon sun.",
    map: [
      { label: "Port aux Basques", lat: 47.57, lon: -59.14 },
      { label: "Corner Brook", lat: 48.95, lon: -57.95 },
      { label: "Tablelands", lat: 49.47, lon: -57.95 },
      { label: "Norris Point", lat: 49.52, lon: -57.88 },
    ],
  },
  {
    n: "05",
    region: "Gros Morne",
    leg: "Western Brook Pond",
    title: "A thousand feet of rock, and no way in",
    subtitle: "A landlocked fjord, and a silence you can hear.",
    photo: "westernBrook",
    wake: "Neddies Harbour Inn, Norris Point.",
    breakfast: "A proper breakfast at the inn — you'll want it before the walk.",
    drive: "≈ 40 min north to the Western Brook Pond trailhead.",
    stops: [
      { name: "Western Brook Pond trail", time: "45 min each way", note: "A flat 3 km across bog and fen to the water's edge, cliffs rising ahead the whole way." },
      { name: "Fjord boat tour", time: "2 hr", note: "A small [boat tour](https://www.bontours.ca/) threads a landlocked fjord beneath billion-year cliffs and hanging waterfalls." },
    ],
    lunch: "A packed hamper from the inn, eaten at the trailhead or on the boat.",
    afternoon: "The walk back; then the Coastal Trail, or an unapologetic nap.",
    hotel: "Neddies Harbour Inn — a second, restful night.",
    dinner: "Chanterelles again, or the Old Loft in Woody Point across the bay.",
    evening: "Stargazing from Norris Point — a genuinely dark sky; the Milky Way if it's clear.",
    charging: "Top up in Rocky Harbour; Level 2 at the inn overnight. No range anxiety here.",
    walking: "Moderate — 6 km round trip on the flat, plus the boat.",
    rainy: "The boat runs in most weather — low cloud makes the cliffs more dramatic, not less. Otherwise the Discovery Centre and a bakery afternoon.",
    wildlife: "Bald eagles over the pond, moose in the fens, common loons; caribou on the high plateau above.",
    memory: "The boat cuts its engine beneath two thousand feet of rock — and there is no sound at all.",
    map: [
      { label: "Norris Point", lat: 49.52, lon: -57.88 },
      { label: "Western Brook Pond", lat: 49.78, lon: -57.83 },
    ],
  },
  {
    n: "06",
    region: "The Viking Trail",
    leg: "Gros Morne → L'Anse aux Meadows",
    title: "The road turns north",
    subtitle: "Up the coast to the top of the island, where the land runs out.",
    photo: "vikingTrail",
    wake: "Neddies Harbour Inn, a final Bonne Bay morning.",
    breakfast: "Breakfast at the inn, then fuel and provisions for the peninsula.",
    drive: "≈ 4 hr 30 min north on Route 430 — the Viking Trail, tundra on one side, the Gulf on the other.",
    stops: [
      { name: "Arches Provincial Park", time: "20 min", note: "Sea-carved limestone arches right at the roadside." },
      { name: "Port au Choix", time: "1 hr", note: "Four thousand years of Maritime Archaic and Dorset history on a windswept point." },
    ],
    lunch: "The Anchor Café, Port au Choix, or a picnic at Arches.",
    afternoon: "Arrive at the northern tip; the first look at the Norse coast as the light goes long.",
    hotel: "Quirpon Lighthouse Inn (a whale-watching island reached by boat) or the Valhalla Lodge B&B.",
    dinner: "The Norseman Restaurant, L'Anse aux Meadows — the finest table this far north, iceberg-chilled.",
    evening: "Whale-watching from the shore at dusk; grounded icebergs in the tickle early in the season.",
    charging: "Fast-charge in Deer Lake before turning north — then plan the peninsula around Level 2 at lodgings. This is the leg to charge conservatively; it's easily done.",
    walking: "Easy today — the site walking is tomorrow.",
    rainy: "Shorten the roadside stops; the Port au Choix visitor centre is indoor and excellent.",
    wildlife: "Humpback and minke whales off the tip, moose along the road, seabirds, caribou near St. Anthony.",
    memory: "Nine o'clock light, gold on the water, the whole continent narrowing to a single point ahead of you.",
    map: [
      { label: "Norris Point", lat: 49.52, lon: -57.88 },
      { label: "Arches", lat: 49.98, lon: -57.79 },
      { label: "Port au Choix", lat: 50.71, lon: -57.35 },
      { label: "L'Anse aux Meadows", lat: 51.6, lon: -55.53 },
    ],
  },
  {
    n: "07",
    region: "The far north",
    leg: "L'Anse aux Meadows → central Newfoundland",
    title: "A thousand years early",
    subtitle: "The only Norse site in North America — then the long road back down.",
    photo: "lanseAuxMeadows",
    wake: "At the northern tip, whales possibly working the water below.",
    breakfast: "At the lodge, unhurried.",
    drive: "A long leg — ≈ 6 hr total, south down the peninsula and east across the island. Break it with the day's stops.",
    stops: [
      { name: "[L'Anse aux Meadows NHS](https://parks.canada.ca/lhn-nhs/nl/meadows)", time: "2 hr 30 min", note: "Sod longhouses on a windswept meadow — the only confirmed Norse settlement in North America. Norstead's living-history village sits next door." },
      { name: "St. Anthony", time: "1 hr", note: "The Grenfell historic sites and the iceberg lookout at Fishing Point." },
    ],
    lunch: "The Lightkeeper's Café, St. Anthony, over iceberg alley.",
    afternoon: "The drive itself — boreal forest, tuckamore, the occasional moose. Podcast country.",
    hotel: "[Anchor Inn](https://www.anchorinn.ca/) Hotel, Twillingate (arrive evening) — or break in Grand Falls-Windsor if the day runs long.",
    dinner: "Georgie's at the [Anchor Inn](https://www.anchorinn.ca/), or a lobster from the pool at Doyle Sansome & Sons in Crow Head.",
    evening: "Arrive to harbour lights and an early night; the coast is tomorrow.",
    charging: "Fast-charge in Deer Lake, then again in Grand Falls-Windsor — both on Route 1, both timed to a meal or a leg-stretch.",
    walking: "Easy — the Norse site is boardwalk and grass.",
    rainy: "The site's interpretive centre is world-class and indoor; the long drive is weather-proof.",
    wildlife: "Icebergs early in the season, whales off St. Anthony, moose on the evening drive.",
    memory: "Standing where the first Europeans in North America stood, a thousand years ahead of everyone else, the same wind off the same sea.",
    map: [
      { label: "L'Anse aux Meadows", lat: 51.6, lon: -55.53 },
      { label: "St. Anthony", lat: 51.37, lon: -55.6 },
      { label: "Grand Falls-Windsor", lat: 48.93, lon: -55.66 },
      { label: "Twillingate", lat: 49.67, lon: -54.77 },
    ],
  },
  {
    n: "08",
    region: "The northeast coast",
    leg: "Twillingate · Notre Dame Bay",
    title: "Where the whales come in",
    subtitle: "A working harbour, a lighthouse headland, and the exhale you feel in your chest.",
    photo: "whales",
    wake: "[Anchor Inn](https://www.anchorinn.ca/), Twillingate.",
    breakfast: "At the inn, or a harbour café with the boats going out.",
    drive: "Local — short hops around the islands.",
    stops: [
      { name: "Long Point Lighthouse", time: "1 hr", note: "Red-and-white on a high headland; scan for spouts and, early in the season, icebergs." },
      { name: "Whale & iceberg boat tour", time: "2 hr", note: "Out into Notre Dame Bay among humpbacks — spouts, flukes, and the occasional breach." },
    ],
    lunch: "Doyle Sansome & Sons, Crow Head — lobster from the pool beside your table.",
    afternoon: "The boat tour, then the studios and stages of the harbour.",
    hotel: "[Anchor Inn](https://www.anchorinn.ca/) Hotel (second night), or the Toulinguet Inn.",
    dinner: "Georgie's, followed by a glass at the [Auk Island Winery](https://www.aukislandwinery.com/) — berry wine made with iceberg water.",
    evening: "A kitchen party of live traditional music, or the Split Rock lookout at sunset.",
    charging: "Level 2 at the inn; the nearest fast-charge is Gander or Lewisporte — plan the day so you never need it.",
    walking: "Easy–moderate — lighthouse headland and harbour paths.",
    rainy: "Twillingate Museum, the [Auk Island Winery](https://www.aukislandwinery.com/) tasting, the Prime Berth fishing-heritage centre.",
    wildlife: "Humpback whales up close, bald eagles, puffins on the offshore stacks, icebergs early in the season.",
    memory: "A humpback surfacing an oar's length from the boat, the breath loud enough to feel.",
    map: [
      { label: "Twillingate", lat: 49.67, lon: -54.77 },
      { label: "Long Point", lat: 49.68, lon: -54.8 },
      { label: "Notre Dame Bay", lat: 49.55, lon: -54.6 },
    ],
  },
  {
    n: "09",
    region: "Fogo Island",
    leg: "Twillingate → Farewell ferry → Fogo Island",
    title: "An island off an island",
    subtitle: "The edge of the edge, and a room the size of the weather.",
    photo: "fogoInn",
    wake: "Twillingate, an easy morning.",
    breakfast: "A quick breakfast; arrive early for the ferry — it fills.",
    drive: "≈ 1 hr to Farewell, then a ≈ 45 min ferry to Fogo Island.",
    stops: [
      { name: "Fogo Island ferry", time: "45 min", note: "The crossing from Farewell — arrive at the terminal well ahead in summer.", ferry: true },
      { name: "Brimstone Head", time: "45 min", note: "One of the Flat Earth Society's four 'corners of the earth' — granite, wind, and open ocean." },
    ],
    lunch: "Nicole's Café, Joe Batt's Arm — cod tongues and a bakeapple dessert.",
    afternoon: "Settle in; the community art studios, the harbours of Joe Batt's Arm and Tilting.",
    hotel: "[Fogo Island Inn](https://fogoislandinn.ca/) — the reason the rest of the trip feels effortless.",
    dinner: "The [Fogo Island Inn](https://fogoislandinn.ca/) dining room — foraged, hyper-local, extraordinary. Book far ahead.",
    evening: "A wood-fired sauna on the rocks, then the rooftop hot tubs under a full sky of stars.",
    charging: "The Inn has EV charging — plug in for both nights. There is no fast charge on the island; none is needed.",
    walking: "Easy — village lanes and short headland trails.",
    rainy: "The Inn is a destination in itself: the studios, the gallery, a fire, the sea doing the rest.",
    wildlife: "Caribou on the barrens, foxes, seabirds; whales offshore; pack ice in spring.",
    memory: "The ferry pulling away from the mainland again — this time to an island off an island, the far edge of everything.",
    map: [
      { label: "Twillingate", lat: 49.67, lon: -54.77 },
      { label: "Farewell", lat: 49.28, lon: -54.42 },
      { label: "Fogo Island", lat: 49.67, lon: -54.18, ferry: true },
    ],
  },
  {
    n: "10",
    region: "Fogo Island",
    leg: "A day with nothing in it",
    title: "Nowhere to be",
    subtitle: "The rest chapter — built in on purpose, so nothing after it feels like effort.",
    photo: "fogo",
    wake: "[Fogo Island Inn](https://fogoislandinn.ca/) — no alarm.",
    breakfast: "A slow breakfast by the window; the weather is the only agenda.",
    drive: "None. Today has nothing in it, deliberately.",
    stops: [
      { name: "A walk with a community host", time: "2 hr", note: "A local leads you over the barrens and along the shore — the island explained by someone who is it." },
      { name: "Tilting", time: "1 hr 30 min", note: "An Irish outport and National Historic District of saltbox houses and fishing stages." },
    ],
    lunch: "Growlers ice cream in Joe Batt's Arm; the Bangbelly Café.",
    afternoon: "A boat with a local, a beach with no one on it — or nothing at all.",
    hotel: "[Fogo Island Inn](https://fogoislandinn.ca/) — a second night.",
    dinner: "The Inn again; ask for the story behind each plate.",
    evening: "Stargazing from the rocks — the Milky Way over open ocean, no light for a hundred miles east.",
    charging: "Inn Level 2 — you leave tomorrow with a full battery.",
    walking: "As little or as much as you like.",
    rainy: "The perfect place for it — sauna, gallery, a book by that enormous window.",
    wildlife: "Caribou, arctic hare, foxes, whales offshore, seabirds; the occasional late iceberg.",
    memory: "A whole day whose only plan was to watch the weather change over the Atlantic.",
    map: [
      { label: "Joe Batt's Arm", lat: 49.73, lon: -54.17 },
      { label: "Tilting", lat: 49.71, lon: -54.05 },
    ],
  },
  {
    n: "11",
    region: "The Bonavista Peninsula",
    leg: "Fogo Island → Trinity",
    title: "Sea stacks and a painted harbour",
    subtitle: "Back to the mainland of the island, and one of its most beautiful villages.",
    photo: "bonavista",
    wake: "[Fogo Island Inn](https://fogoislandinn.ca/) — a last island morning.",
    breakfast: "At the Inn, then the morning ferry back to Farewell.",
    drive: "≈ 45 min ferry, then ≈ 3 hr 30 min to the Bonavista Peninsula.",
    stops: [
      { name: "Fogo ferry to Farewell", time: "45 min", note: "The island releases you; the road turns south and east.", ferry: true },
      { name: "Skerwink Trail, Port Rexton", time: "2 hr", note: "A 5.3 km coastal loop past sea stacks, with whales often working the water below." },
    ],
    lunch: "Two Whales Coffee Shop, Port Rexton, or the [Bonavista Social Club](https://www.bonavistasocialclub.com/) (wood-fired, farm-to-table — book ahead).",
    afternoon: "Trinity village — the Green, the mercantile houses, the Rising Tide Theatre.",
    hotel: "[Artisan Inn](https://trinityvacations.com/), Trinity — restored heritage houses on the harbour.",
    dinner: "The Twine Loft at the [Artisan Inn](https://trinityvacations.com/) — a set menu, one seating, candlelight over the water.",
    evening: "A seasonal pageant at Rising Tide, or the sunset from Fort Point.",
    charging: "Fast-charge in Gander or Clarenville en route; Level 2 in Trinity overnight.",
    walking: "Moderate if you walk the Skerwink; easy if you don't.",
    rainy: "Trinity's museums and merchant houses; the [Bonavista Social Club](https://www.bonavistasocialclub.com/) lunch stretched pleasantly long.",
    wildlife: "Whales off the Skerwink, puffins, bald eagles.",
    memory: "The Skerwink Trail rounding a headland to a row of sea stacks with a whale spouting below.",
    map: [
      { label: "Fogo Island", lat: 49.67, lon: -54.18 },
      { label: "Farewell", lat: 49.28, lon: -54.42, ferry: true },
      { label: "Clarenville", lat: 48.17, lon: -53.97 },
      { label: "Trinity", lat: 48.37, lon: -53.36 },
    ],
  },
  {
    n: "12",
    region: "Bonavista & the southwest Avalon",
    leg: "Trinity → Cape Bonavista → Cape St. Mary's",
    title: "A rock alive with wings",
    subtitle: "Puffins at arm's reach, then thirty thousand gannets on a single stack of stone.",
    photo: "capeStMarys",
    wake: "[Artisan Inn](https://trinityvacations.com/), Trinity.",
    breakfast: "At the inn, then out to the cape.",
    drive: "A big transit day — ≈ 4 hr 30 min south to Cape St. Mary's, the day's anchor.",
    stops: [
      { name: "Cape Bonavista & Elliston", time: "2 hr", note: "The Cape Bonavista lighthouse and the Dungeon sea arches; then Elliston, where puffins nest within arm's reach of the headland." },
      { name: "Cape St. Mary's · Bird Rock", time: "1 hr 30 min", note: "A 1 km cliff-edge walk to a sea stack packed with 30,000+ nesting northern gannets, a gap's width away." },
    ],
    lunch: "The Boreal Diner, Bonavista (superb), or a picnic for the long road south.",
    afternoon: "The gannet colony at Cape St. Mary's in the late light — a wall of sound and wings.",
    hotel: "Bird Island Resort at Point Lance, or an inn in Placentia.",
    dinner: "Simple and local — this is a wild corner of the map, and better for it.",
    evening: "The roar of thirty thousand birds carrying up the cliff at dusk.",
    charging: "Fast-charge in Clarenville and again near Whitbourne/Placentia on Route 1 — the Avalon is well covered.",
    walking: "Easy–moderate — 1 km each way to Bird Rock on a cliff-edge path; mind the drop.",
    rainy: "The gannets don't mind rain, and fog makes Bird Rock more dramatic. The reserve's interpretive centre is indoors.",
    wildlife: "Northern gannets in the tens of thousands, murres, kittiwakes, razorbills — and the Avalon caribou herd on the barrens along the drive in.",
    memory: "The wall of sound and wings at Bird Rock — a single stack of stone alive with thirty thousand birds.",
    map: [
      { label: "Trinity", lat: 48.37, lon: -53.36 },
      { label: "Bonavista", lat: 48.65, lon: -53.11 },
      { label: "Cape St. Mary's", lat: 46.82, lon: -54.18 },
      { label: "Placentia", lat: 47.24, lon: -53.96 },
    ],
  },
  {
    n: "13",
    region: "The Irish Loop",
    leg: "Cape St. Mary's → Ferryland → St. John's",
    title: "A blanket on the headland",
    subtitle: "A hamper, a lighthouse, the ocean on three sides — and no hurry at all.",
    photo: "ferryland",
    wake: "Point Lance or Placentia, the wild edge of the Avalon.",
    breakfast: "At the lodge, then around the southern shore.",
    drive: "≈ 2 hr 30 min up the Irish Loop to St. John's, with stops.",
    stops: [
      { name: "Colony of Avalon, Ferryland", time: "1 hr", note: "A live 1620s archaeological dig — one of the earliest English settlements in North America." },
      { name: "Ferryland Lighthouse", time: "1 hr 30 min", note: "A grassy headland running out to a small lighthouse, ocean on three sides." },
    ],
    lunch: "Lighthouse Picnics, Ferryland — a wool blanket on the cliff and a hamper of local food. Book ahead; it is the point of the day.",
    afternoon: "North to St. John's; the city rising in its bowl of hills. Check in and wander Water Street.",
    hotel: "JAG Hotel or ALT Hotel, downtown St. John's — design-forward and central.",
    dinner: "Raymonds if you can get in (one of Canada's best), or Mallard Cottage in Quidi Vidi, or Adelaide Oyster House.",
    evening: "George Street for a set of live traditional music — and, if the mood takes you, a proper 'screech-in'.",
    charging: "St. John's is thick with fast and Level 2 chargers; charge at the hotel overnight.",
    walking: "Easy — a headland picnic and city streets.",
    rainy: "The Colony of Avalon's interpretation centre is indoor; Lighthouse Picnics runs under the eaves; the Rooms museum awaits in town.",
    wildlife: "A humpback often works the bay directly below the Ferryland picnic; seabirds; the odd summer iceberg.",
    memory: "Lunch on a wool blanket at the lighthouse, a whale spouting in the bay below, in no hurry whatsoever.",
    map: [
      { label: "Placentia", lat: 47.24, lon: -53.96 },
      { label: "Ferryland", lat: 47.03, lon: -52.87 },
      { label: "St. John's", lat: 47.56, lon: -52.71 },
    ],
  },
  {
    n: "14",
    region: "St. John's",
    leg: "The city & Signal Hill",
    title: "The whole Atlantic, below you",
    subtitle: "The oldest city in North America, row houses like paint chips, a hill above the Narrows.",
    photo: "signalHill",
    wake: "Downtown St. John's.",
    breakfast: "Rocket Bakery, or a long brunch at Mallard Cottage in Quidi Vidi.",
    drive: "Minimal — the city and Signal Hill on foot and a few short hops.",
    stops: [
      { name: "Jellybean Row & the harbour", time: "2 hr", note: "The saturated row houses climbing the hill, and Water Street — the oldest commercial street on the continent." },
      { name: "[Signal Hill · Cabot Tower](https://parks.canada.ca/lhn-nhs/nl/signalhill)", time: "2 hr", note: "Where Marconi received the first transatlantic wireless signal; the North Head Trail runs the cliffs above the Narrows." },
    ],
    lunch: "Chinched, Portobello's, or an oyster hour at Adelaide.",
    afternoon: "Signal Hill and the North Head Trail, then Quidi Vidi village and its brewery.",
    hotel: "JAG or ALT (second night).",
    dinner: "Mallard Cottage — a long, convivial Newfoundland feast in a restored heritage house.",
    evening: "Sunset from Signal Hill over the whole city and the open Atlantic; a quiet pint after at the Duke of Duckworth.",
    charging: "Anywhere in the city; charge to full overnight — tomorrow you leave from Argentia.",
    walking: "Moderate — the North Head Trail is cliff-edge with stairs.",
    rainy: "The Rooms is a full indoor day on its own; the Johnson Geo Centre, Quidi Vidi Brewery, the shops of Water Street.",
    wildlife: "Whales in the Narrows below Signal Hill; seabirds; occasionally a berg parked off the harbour mouth.",
    memory: "The whole city glowing below Cabot Tower at last light, the Atlantic going dark all the way to the horizon.",
    map: [
      { label: "St. John's", lat: 47.56, lon: -52.71 },
      { label: "Signal Hill", lat: 47.57, lon: -52.68 },
      { label: "Quidi Vidi", lat: 47.58, lon: -52.68 },
    ],
  },
  {
    n: "15",
    region: "The easternmost light",
    leg: "Cape Spear sunrise → Argentia ferry → home",
    title: "The sun reaches you first",
    subtitle: "First light on the continent, and then the island lets you go.",
    photo: "capeSpear",
    wake: "Before dawn, in the dark — the alarm you'll be glad you set.",
    breakfast: "Coffee in a thermos; breakfast can wait until the light has come.",
    drive: "≈ 20 min to Cape Spear for sunrise, then ≈ 1 hr 30 min to the Argentia ferry.",
    stops: [
      { name: "[Cape Spear](https://parks.canada.ca/lhn-nhs/nl/spear)", time: "1 hr", note: "The easternmost point of North America — the first place the sun touches the continent. The old lighthouse and a WWII gun battery stand above the surf." },
      { name: "Argentia ferry terminal", time: "boarding", note: "The long crossing back to North Sydney — the island receding into soft light.", ferry: true },
    ],
    lunch: "Something simple near Argentia, or provisions carried aboard.",
    afternoon: "The Argentia ferry to North Sydney — a restful crossing of roughly sixteen hours (seasonal).",
    hotel: "A cabin aboard the ferry — sleep as Newfoundland lets go behind you.",
    dinner: "Aboard, watching the wake trail into the dusk.",
    evening: "The deck one last time. What stays.",
    charging: "Charge to 100% in St. John's before leaving — there's no charging on the crossing; the drive home resumes from North Sydney.",
    walking: "Easy — the short walk out to the Cape Spear point and back.",
    rainy: "Sunrise arrives even through cloud — the light still reaches here first. The ferry is entirely weather-proof.",
    wildlife: "Whales off Cape Spear at first light, seabirds escorting the ferry, a final gannet or two.",
    memory: "Standing at the very edge of the continent as the sun clears the Atlantic — the first light in North America, and it falls on the two of you.",
    map: [
      { label: "St. John's", lat: 47.56, lon: -52.71 },
      { label: "Cape Spear", lat: 47.52, lon: -52.62 },
      { label: "Argentia", lat: 47.3, lon: -53.99, ferry: true },
    ],
  },
];
