import type { TripDay } from "@/lib/trip-types";
import { NS_PHOTOS } from "./photos";

/**
 * NOVA SCOTIA — THE JOURNEY, DAY BY DAY  (itinerary v2.1)
 * ------------------------------------------------------
 * A relaxed 12-day 2026 road trip for Darren & Melissa. Reconciled to the
 * "Nova Scotia Hotel Master Plan V2.1" — the single source of truth — which
 * favours value over luxury: honest, well-reviewed inns that support the trip
 * instead of becoming it.
 *
 * Fixed points: the Yarmouth -> Bar Harbor CAT ferry on Monday, August 17
 * (booked). Locked overnights: Bangor (Aug 7), St. Andrews / Kennedy House,
 * Alma / Parkland Village Inn, Halifax / The Prince George, Lunenburg / Sail
 * Inn, Baddeck / Telegraph House, Chéticamp / Outback Inn, Ingonish / Seascape,
 * Yarmouth / Comfort Inn, and Rockland / Rockland Harbor Hotel (replacing Bar
 * Harbor). Added by request during planning: Blue Rocks, Ovens Natural Park,
 * and Meat Cove.
 *
 * Restaurants, inns, parks, and the ferry are linked with [label](url) — verify
 * hours and book ahead; timings, sunset times, and distances are honest
 * estimates for a day that should never feel rushed.
 *
 * NOTE: the small route-map graphics still show the earlier Portland / Bar
 * Harbor framing; regenerating those basemaps is a tracked follow-up.
 */

export const NS_DAYS: TripDay[] = [
  {
    n: "01",
    date: "Friday · August 7, 2026",
    region: "The gentle launch",
    leg: "Salt Point, NY → Bangor, Maine",
    title: "North, without the alarm clock",
    subtitle: "The one long day — the coast of Maine by lunch, and Bangor by dinner.",
    photo: NS_PHOTOS.portland,
    morningLocation: "Home in Salt Point, at a civilized hour — coffee on the porch, the car already packed for the trip's longest drive.",
    breakfast: "Something quick at home, or a pastry from the village. The real eating starts on the coast.",
    drive: "≈ 7 hr moving · 700 km — Taconic to the Mass Pike, then I-95 up through New Hampshire and the Maine coast to Bangor. All highway, all easy — just long, so today carries the miles and tomorrow is short.",
    stops: [
      { name: "Portsmouth, New Hampshire", time: "45 min", note: "A stretch and a harbour walk where New England first smells like the sea." },
      { name: "Portland Head Light, Cape Elizabeth", time: "45 min", note: "The most photographed lighthouse in Maine, right off the highway — a soft first postcard for Darren's camera, and a lobster-roll lunch in the Old Port before you point the car north." },
    ],
    lunch: "Portland — a lobster roll or cold oysters in the Old Port; the last big-city meal before Canada.",
    afternoon: "The easy run up I-95 from Portland to Bangor — inland and quick, the coast behind you and Canada a short hop tomorrow.",
    hotel: "[Country Inn at the Mall](https://countryinnatthemall.net), Bangor — the trip's value pick: 9.0 from 2,600+ guests, free breakfast and parking, and perfectly placed to make tomorrow's border run short.",
    dinner: "Bangor — Timber Kitchen & Bar (wood-fired) or the Sea Dog Brewing pub; downtown's indie spots are a 10-minute hop if you want livelier.",
    evening: "An early, easy night after the long haul — you have bought yourself a short, gentle Day 2.",
    charging: "Superchargers all the way up I-95 (Sturbridge, Portland, Augusta) — charge over lunch in Portland, then top up in Bangor (Broadway); Level 2 at the hotel overnight. Nothing to plan.",
    walking: "Easy — town strolls only.",
    rainy: "The Portland Museum of Art (Homer and the Wyeths) breaks the drive; the day is mostly windshield either way, and a rainy first day costs you nothing.",
    detailedPlan: [
      { time: "7:30 AM", label: "Depart Salt Point", detail: "Car packed the night before; coffee for the road." },
      { time: "12:00 PM", label: "Portsmouth, NH — 45 min", detail: "Leg-stretch and a first harbour smell." },
      { time: "1:00 PM", label: "Portland, ME — lunch + Portland Head Light", detail: "≈ 1 hr 15 — lobster roll, then the lighthouse. Supercharge here." },
      { time: "2:30 PM", label: "Drive Portland → Bangor", detail: "≈ 2 hr up I-95, inland and quick." },
      { time: "4:45 PM", label: "Arrive Bangor — Country Inn at the Mall", detail: "Check in, unwind." },
      { time: "6:45 PM", label: "Dinner — Timber Kitchen & Bar / Sea Dog" },
      { time: "7:52 PM", label: "Sunset ≈ 7:52 PM" },
      { time: "10:30 PM", label: "Early night", detail: "Long day done; tomorrow is short and gentle." },
    ],
    memory: "A lobster roll under Portland Head Light with the Atlantic finally in the frame — then the satisfying tick of the long day falling behind you as Bangor arrives.",
    map: [
      { label: "Salt Point", lat: 41.87, lon: -73.8 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
    ],
  },
  {
    n: "02",
    date: "Saturday · August 8, 2026",
    region: "Into Canada, softly",
    leg: "Bangor, Maine → St. Andrews by-the-Sea, New Brunswick",
    title: "The border you barely feel",
    subtitle: "A short, easy morning across at Calais — and a whole afternoon in the gentlest town in Canada.",
    photo: NS_PHOTOS.standrews,
    morningLocation: "Bangor — an unhurried breakfast; today is the reward for yesterday, barely three hours to the border.",
    breakfast: "A proper Maine breakfast at the Governor's Restaurant, and a coffee for Route 9.",
    drive: "≈ 3 hr · 240 km — the quiet Route 9 'Airline' east through the Maine woods to Calais, over the border at St. Stephen, then a short hop to St. Andrews. The road empties the whole way.",
    stops: [
      { name: "St. Stephen, New Brunswick", time: "1 hr", note: "The Ganong chocolate town, right at the border — the Chocolate Museum and a bag of chicken-bone candy for the road." },
      { name: "Kingsbrae Garden, St. Andrews", time: "1.5 hr", note: "Twenty-seven acres of coastal garden above Passamaquoddy Bay — the soft, unhurried arrival into Canada, with time to spare because the drive was short." },
    ],
    lunch: "St. Stephen or St. Andrews — a light bite; you have all afternoon in town.",
    afternoon: "Cross into Canada (passports ready; the crossing here is calm and quick), then settle into St. Andrews — Kingsbrae Garden, the long wharf, or a whale-watch boat out onto the bay.",
    hotel: "[Kennedy House](https://www.kennedy-house.ca) — an excellent-value inn (8.5, 700+ reviews) a short walk from Water Street; half the price of the grand resort, in a town you came for anyway.",
    dinner: "[Rossmount Inn](https://www.rossmountinn.com/), one of the Maritimes' best tables (reserve), or the Niger Reef Tea House on the water.",
    evening: "Sunset from the wharf; whales sometimes roll through the bay off the point — and the first real spread of stars once the light goes.",
    charging: "Charge full in Bangor before Route 9 (no chargers on the Airline); Canadian charging begins around St. Stephen and Saint John. Kennedy House / town Level 2 overnight.",
    walking: "Easy — gardens and a flat seaside town.",
    rainy: "Kingsbrae's pavilions, the Ganong Chocolate Museum, or the Huntsman Fundy Discovery Aquarium.",
    sky: "If skies are clear, the wharf gives your first real spread of stars — light pollution thins the moment you leave the I-95 corridor. An easy, optional first look up.",
    detailedPlan: [
      { time: "9:00 AM", label: "Breakfast in Bangor — Governor's" },
      { time: "10:00 AM", label: "Depart east on Route 9", detail: "Charge full first; the Airline has no chargers." },
      { time: "12:15 PM", label: "St. Stephen border + Ganong — ≈ 1 hr", detail: "Chocolate Museum; passports ready." },
      { time: "2:00 PM", label: "Arrive St. Andrews — Kennedy House", detail: "Check in, drop bags." },
      { time: "2:45 PM", label: "Kingsbrae Garden / the wharf — ≈ 1.5 hr", detail: "Or a whale-watch boat if one's sailing." },
      { time: "7:00 PM", label: "Dinner — Rossmount Inn (reserve)" },
      { time: "8:20 PM", label: "Sunset ≈ 8:20 PM ADT", detail: "First stars from the wharf if it's clear." },
      { time: "10:30 PM", label: "Bedtime" },
    ],
    memory: "Crossing into Canada before lunch and feeling the whole trip downshift — chocolate in hand, a garden above the bay, and a long, slow afternoon with nowhere you had to be.",
    map: [
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Wiscasset", lat: 44.0, lon: -69.66 },
      { label: "St. Stephen", lat: 45.19, lon: -67.28 },
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
    ],
  },
  {
    n: "03",
    date: "Sunday · August 9, 2026",
    region: "The highest tides on earth",
    leg: "St. Andrews → Hopewell Rocks → Alma & the Bay of Fundy",
    title: "Walk the floor of the ocean",
    subtitle: "Time the day to the tide, and stand where the sea will be.",
    photo: NS_PHOTOS.fundy,
    morningLocation: "St. Andrews — a good breakfast, then east along the Fundy shore (check today's low-tide time first; the whole day pivots on it).",
    breakfast: "Honeybeans in town, or the inn; a coffee for the coast road.",
    drive: "≈ 3 hr 15 min · 260 km to Hopewell, plus the Fundy park loop — an easy day of short hops between big views.",
    stops: [
      { name: "Saint John, NB", time: "1 hr", note: "The uptown red-brick core and the Reversing Falls, where the Fundy tide runs the river backwards. A Supercharger and lunch here." },
      { name: "[Hopewell Rocks](https://www.thehopewellrocks.ca/)", time: "1.5–2 hr", note: "Descend the stairs to the actual sea floor at low tide and walk among tree-topped flowerpot stacks carved by forty vertical feet of tide." },
    ],
    lunch: "Saint John on the way, or hold out for Alma — lobster and chowder at the Tides, and a Kelly's sticky bun the size of your hand.",
    afternoon: "Hopewell Rocks at low tide, then Cape Enrage's cliffs; the sea floor you walked at noon is under three storeys of water by dusk.",
    hotel: "[Parkland Village Inn](https://www.parklandvillageinn.com), Alma — oceanfront in the village, on-site restaurant, walk to the Fundy park gate. Book direct and early — Alma sells out; the verified fallback is the Four Points in Moncton (~45 min).",
    dinner: "The Tides at the Parkland, or Tipsy Tails — Fundy scallops and Alma lobster, the tide coming in outside the window.",
    evening: "Back to the flats at dusk to watch the water swallow the ground you stood on — the same view, twice, transformed.",
    charging: "Superchargers in Saint John and Moncton, both near food. Alma is remote — arrive with a good charge and top up before the park; the inn has Level 2.",
    walking: "Easy–moderate — stairs down to the ocean floor at Hopewell; flat clifftop paths at Cape Enrage.",
    rainy: "The tide performs in any weather; the Hopewell interpretive centre and Cape Enrage's café keep you dry between shows.",
    sky: "Best chance yet: Fundy National Park is a certified Dark Sky Preserve. If it's clear and you've stayed in Alma rather than Moncton, this is the trip's first great dark sky — the Milky Way over the bay, no city glow.",
    detailedPlan: [
      { time: "8:30 AM", label: "Breakfast — Honeybeans", detail: "Check today's low-tide time; the day pivots on it." },
      { time: "9:30 AM", label: "Depart east along the Fundy shore" },
      { time: "11:00 AM", label: "Saint John — Reversing Falls, ≈ 1 hr", detail: "Supercharge + a bite." },
      { time: "1:30 PM", label: "Hopewell Rocks — ≈ 1.5–2 hr", detail: "Walk the sea floor at low tide." },
      { time: "3:30 PM", label: "Alma — late lunch + Kelly's sticky bun" },
      { time: "4:30 PM", label: "Arrive Parkland Village Inn (booked direct)" },
      { time: "6:30 PM", label: "Dinner — the Tides / Tipsy Tails" },
      { time: "8:33 PM", label: "Sunset ≈ 8:33 PM ADT", detail: "Then the flats at high tide, transformed." },
      { time: "11:00 PM", label: "Stargaze if clear (Dark Sky Preserve), then bed" },
    ],
    memory: "Standing on the ocean floor at noon, then watching four storeys of tide quietly erase it by dark — and a Fundy sky full of stars over Alma.",
    map: [
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
      { label: "Saint John", lat: 45.27, lon: -66.06 },
      { label: "Hopewell Rocks", lat: 45.82, lon: -64.58 },
      { label: "Alma", lat: 45.6, lon: -64.95 },
    ],
  },
  {
    n: "04",
    date: "Monday · August 10, 2026",
    region: "Across into Nova Scotia",
    leg: "Alma → Wolfville & Grand-Pré → Halifax",
    title: "Wine country by the world's biggest tide",
    subtitle: "Cross into Nova Scotia through orchards and dykelands; arrive in Halifax by evening.",
    photo: NS_PHOTOS.wolfville,
    morningLocation: "The Fundy shore — a slow start; the drive into Nova Scotia over the Tantramar marshes is flat and painless.",
    breakfast: "The inn, or a last Alma sticky bun for the road.",
    drive: "≈ 3 hr to Wolfville, then 1 hr on to Halifax · 330 km total — over the isthmus at Amherst into Nova Scotia.",
    stops: [
      { name: "Grand-Pré National Historic Site", time: "1 hr", note: "A UNESCO landscape of Acadian dykelands and the moving story of the 1755 deportation — quiet, beautiful, and grounding." },
      { name: "Wolfville wineries", time: "1.5–2 hr", note: "[Lightfoot & Wolfville](https://www.lightfootandwolfville.com/) or [Domaine de Grand Pré](https://www.grandprewines.com/) — Nova Scotia's crisp Tidal Bay whites, tasted on a patio above the flats." },
    ],
    lunch: "Le Caveau at [Domaine de Grand Pré](https://www.grandprewines.com/), or the [Lightfoot & Wolfville](https://www.lightfootandwolfville.com/) terrace — valley-to-table with the Bay of Fundy shining below.",
    afternoon: "Walk the Grand-Pré dykelands, then the genuinely easy hour into Halifax — the biggest city of the trip arrives gently.",
    hotel: "[The Prince George Hotel](https://www.princegeorgehotel.com), Halifax — refined and central, pedway to downtown, steps from the waterfront and Citadel; the smart two-night anchor without the luxury markup.",
    dinner: "[The Bicycle Thief](https://bicyclethief.ca/) on the boardwalk (reserve); or Bar Kismet if you want the local chefs' favourite.",
    evening: "The Halifax waterfront after dark — schooners, buskers, harbour lights, and the longest downtown boardwalk in the world underfoot.",
    charging: "Supercharge in Truro at the midpoint (or New Minas near Wolfville); Enfield and Halifax have Superchargers, and the hotel has valet Level 2 overnight.",
    walking: "Easy — vineyard rows and a flat historic site.",
    rainy: "Tastings are indoors; Grand-Pré's interpretive centre is excellent; and Halifax is a city built for a rainy evening.",
    detailedPlan: [
      { time: "8:30 AM", label: "Breakfast — a last Alma sticky bun" },
      { time: "9:15 AM", label: "Depart over the isthmus into Nova Scotia" },
      { time: "12:15 PM", label: "Grand-Pré NHS — ≈ 1 hr", detail: "Dykelands and the Acadian story." },
      { time: "1:30 PM", label: "Wolfville — lunch + a tasting, ≈ 2 hr", detail: "Le Caveau or Lightfoot & Wolfville. Charge at New Minas." },
      { time: "4:45 PM", label: "Arrive Halifax — The Prince George Hotel" },
      { time: "7:00 PM", label: "Dinner — The Bicycle Thief (reserve)" },
      { time: "8:12 PM", label: "Sunset ≈ 8:12 PM ADT", detail: "Boardwalk after dark." },
      { time: "11:00 PM", label: "Bedtime" },
    ],
    memory: "A glass of Tidal Bay on a vineyard patio, the Bay of Fundy shining below — the moment Nova Scotia stopped being a plan and started being the trip.",
    map: [
      { label: "Alma", lat: 45.6, lon: -64.95 },
      { label: "Amherst", lat: 45.83, lon: -64.21 },
      { label: "Wolfville", lat: 45.09, lon: -64.36 },
      { label: "Halifax", lat: 44.65, lon: -63.57 },
    ],
  },
  {
    n: "05",
    date: "Tuesday · August 11, 2026",
    region: "Halifax, at ease",
    leg: "Halifax — a day out of the car",
    title: "A city that feels like a coastal town",
    subtitle: "Waterfront, Citadel, a museum with a Titanic story — and no driving at all.",
    photo: NS_PHOTOS.halifax,
    morningLocation: "Halifax — coffee on the waterfront; today the car doesn't move and neither do you, faster than you want to.",
    breakfast: "The Seaport Farmers' Market (North America's oldest) for coffee and pastries among the stalls.",
    drive: "None to speak of — this is the day that proves the trip isn't all windshield.",
    stops: [
      { name: "[Halifax Citadel](https://parks.canada.ca/lhn-nhs/ns/halifax)", time: "1.5 hr", note: "The star-shaped hilltop fort, the noon gun, kilted guards, and the whole harbour laid out below." },
      { name: "[Maritime Museum of the Atlantic](https://maritimemuseum.novascotia.ca/)", time: "1.5 hr", note: "The definitive Titanic collection and the story of the 1917 Halifax Explosion — history and engineering in one waterfront hall for Darren." },
      { name: "Halifax Public Gardens", time: "45 min", note: "Formal Victorian gardens, a bandstand, and a bench in the shade — the softest possible city stop." },
    ],
    lunch: "A lobster roll on the boardwalk, or the Battered Fish; keep it light and outdoors.",
    afternoon: "Take the Dartmouth ferry across the harbour and back — the oldest saltwater ferry in North America and, at a few dollars, the best harbour cruise there is.",
    hotel: "The Prince George again — no repacking, no logistics, just a second easy night in the heart of downtown.",
    dinner: "Bar Kismet (a seafood tasting) or the Stubborn Goat gastropub — then live East Coast fiddle at The Carleton.",
    evening: "A pint and a tune at The Carleton or the Lower Deck — the real Maritime warmth, no cover charge on the feeling.",
    charging: "The car rests all day on the hotel's Level 2 — genuinely nothing to think about.",
    walking: "Easy — city strolling entirely at your own pace.",
    rainy: "Everything today has a roof — the museums, the market, the fiddle. A rainy Halifax day is a good day by design.",
    detailedPlan: [
      { time: "8:30 AM", label: "Breakfast — Seaport Farmers' Market" },
      { time: "10:30 AM", label: "Halifax Citadel — ≈ 1.5 hr", detail: "Stay for the noon gun at 12:00." },
      { time: "12:30 PM", label: "Lunch on the boardwalk" },
      { time: "1:30 PM", label: "Maritime Museum of the Atlantic — ≈ 1.5 hr" },
      { time: "3:15 PM", label: "Public Gardens — 45 min · coffee (Java Blend)" },
      { time: "4:15 PM", label: "Dartmouth ferry round-trip — 45 min" },
      { time: "7:00 PM", label: "Dinner — Bar Kismet, then fiddle at The Carleton" },
      { time: "8:11 PM", label: "Sunset ≈ 8:11 PM ADT" },
      { time: "11:30 PM", label: "Bedtime" },
    ],
    memory: "The harbour ferry at dusk, the city gold behind you, realizing you hadn't touched the car in a full day and hadn't missed it once.",
    map: [
      { label: "Halifax", lat: 44.65, lon: -63.57 },
      { label: "Dartmouth", lat: 44.67, lon: -63.57 },
    ],
  },
  {
    n: "06",
    date: "Wednesday · August 12, 2026",
    region: "The South Shore",
    leg: "Halifax → Peggy's Cove → Mahone Bay → Lunenburg",
    title: "Lighthouses, three churches, and a painted town",
    subtitle: "The classic coast — photographed early, tasted slowly, with two hidden corners most people miss.",
    photo: NS_PHOTOS.peggys,
    morningLocation: "Halifax — an early start out along St. Margarets Bay, ahead of the tour buses, to have Peggy's Cove to yourselves.",
    breakfast: "Grab-and-go from Halifax; a proper brunch waits in Mahone Bay.",
    drive: "≈ 2 hr 30 min total across the whole day · 160 km — short, scenic legs with long stops between.",
    stops: [
      { name: "Peggy's Cove", time: "1–1.5 hr", note: "The red-capped light on wave-worn granite. Go early for the low light, the quiet, and the safe new viewing deck — mind the wet black rock." },
      { name: "Mahone Bay", time: "1 hr", note: "The three steepled churches mirrored in a calm bay, and a main street of makers, bakers, and a very good kouign-amann." },
      { name: "Ovens Natural Park", time: "1.5 hr", note: "Added by request: sea caves in the cliffs south of Lunenburg — a coastal boardwalk into booming caverns (the 'Cannon Cave'), and a gold-rush beach you can still pan. A wild, low-key counterpoint to the postcard towns." },
      { name: "Blue Rocks", time: "1 hr", note: "Added by request: a tiny fishing hamlet 10 minutes past Lunenburg — slate-blue ledges, weathered fish shacks, and still water. The photographer's secret of the South Shore; go for golden hour." },
    ],
    lunch: "Mahone Bay — Oh My Cod or Rebecca's; a pastry and a coffee by the water.",
    afternoon: "Into Lunenburg to drop bags, then the pair most visitors miss — the sea caves at Ovens Natural Park, and the blue-slate ledges of Blue Rocks in the low evening light.",
    hotel: "[Sail Inn Lunenburg](https://www.sailinn.ca) — waterfront, sea-view rooms, 200 feet from the UNESCO Old Town; walkable value in the prettiest harbour on the coast.",
    dinner: "Lunenburg — Bar Salvador for tapas (reserve), the Old Fish Factory in the Fisheries Museum, or the Half Shell for oysters.",
    evening: "The waterfront at blue hour — dories, rigging, and reflections; a nightcap on the inn porch.",
    charging: "Supercharge in Bridgewater (ten minutes from Lunenburg, and right by Ovens Natural Park) or back in Halifax; a short-mileage day makes charging an afterthought.",
    walking: "Easy–moderate — Peggy's granite is slick when wet; the Ovens cliff boardwalk has stairs and drops; the towns are flat and gentle.",
    rainy: "The Fisheries Museum of the Atlantic is a superb indoor half-day; Ironworks Distillery for a tasting; Peggy's Cove is at its most dramatic in fog.",
    sky: "Optional and photogenic rather than dark: if the harbour's clear, the Lunenburg and Blue Rocks waterfront scatters soft stars over the rigging — not the trip's darkest sky, but its prettiest for a long exposure.",
    detailedPlan: [
      { time: "7:00 AM", label: "Depart Halifax", detail: "Beat the buses to Peggy's Cove." },
      { time: "8:00 AM", label: "Peggy's Cove — ≈ 1 hr", detail: "Low light, empty granite." },
      { time: "10:00 AM", label: "Mahone Bay — ≈ 1 hr + brunch/coffee" },
      { time: "12:30 PM", label: "Lunenburg — drop bags at Sail Inn, Old Town wander", detail: "Coffee at Laughing Whale." },
      { time: "2:30 PM", label: "Ovens Natural Park — ≈ 1.5 hr", detail: "Sea-cave boardwalk; charge at Bridgewater nearby." },
      { time: "5:30 PM", label: "Blue Rocks — golden hour, ≈ 1 hr", detail: "The photographer's hamlet." },
      { time: "7:30 PM", label: "Dinner — Bar Salvador (reserve)" },
      { time: "8:10 PM", label: "Sunset ≈ 8:10 PM ADT", detail: "Blue hour on the waterfront." },
      { time: "11:00 PM", label: "Nightcap on the porch, then bed" },
    ],
    memory: "Peggy's Cove almost to yourselves at first light, and the blue ledges of Blue Rocks glowing at dusk — the famous coast and its quiet secret, both in one unhurried day.",
    map: [
      { label: "Halifax", lat: 44.65, lon: -63.57 },
      { label: "Peggy's Cove", lat: 44.49, lon: -63.92 },
      { label: "Mahone Bay", lat: 44.45, lon: -64.38 },
      { label: "Lunenburg", lat: 44.38, lon: -64.31 },
    ],
  },
  {
    n: "07",
    date: "Thursday · August 13, 2026",
    region: "Toward Cape Breton",
    leg: "Lunenburg → Baddeck, Cape Breton",
    title: "The long, easy reach to the inland sea",
    subtitle: "A scenic repositioning day that ends on the shore of Bras d'Or Lake.",
    photo: NS_PHOTOS.brasdor,
    morningLocation: "Lunenburg — a last harbour coffee, then north; the day is about arriving somewhere serene, not rushing.",
    breakfast: "A Lunenburg café; pastries and a flat white for the road.",
    drive: "≈ 4 hr 30 min · 430 km — up through the province and over the Canso Causeway onto Cape Breton, broken by good stops.",
    stops: [
      { name: "Truro", time: "30 min", note: "A charge and a leg-stretch; if the tide's right, catch the Salmon River tidal bore rolling upstream." },
      { name: "Antigonish", time: "1 hr", note: "A pretty university town for a relaxed main-street lunch — the last real town before the island." },
      { name: "Canso Causeway & Aulds Cove", time: "20 min", note: "Cross the deepest causeway in the world onto Cape Breton — and charge to 100% at Aulds Cove first: it is the last fast charging before the island's sparse network." },
    ],
    lunch: "Antigonish — a bistro on Main Street; unhurried, good coffee, no rush to the car.",
    afternoon: "Over the causeway and along the shore of Bras d'Or Lake — a vast inland sea — into Baddeck by late afternoon.",
    hotel: "[Telegraph House](https://telegraphhouse.travel), Baddeck — a historic village inn (in operation since 1861, with an Alexander Graham Bell connection), central and great value; Auberge Gisele's is the step-up alternative.",
    dinner: "Baddeck — the community tradition of [Baddeck Lobster Suppers](https://baddecklobstersuppers.ca/) (go early, no reservations), or the Bell Buoy.",
    evening: "The Bras d'Or shore at dusk — glass-calm water, loons calling, the quietest night of the trip so far.",
    charging: "Supercharge in Truro and near New Glasgow on the way, then top to 100% at Aulds Cove before the causeway — Cape Breton has no Superchargers. Baddeck has a FLO fast charger on Highway 105 and the inn has Level 2. This is your staging point for the Cabot Trail.",
    walking: "Easy — a stretch-your-legs travel day.",
    rainy: "The drive is the day and it's comfortable in any weather; if it pours, the [Bell museum](https://parks.canada.ca/lhn-nhs/ns/grahambell) tomorrow is entirely indoors.",
    sky: "Best chance for dark sky tonight: away from the village, the Bras d'Or shore is genuinely dark. If it's clear, step out after dinner — the lake doubles every star.",
    detailedPlan: [
      { time: "8:30 AM", label: "Breakfast — a Lunenburg café" },
      { time: "9:15 AM", label: "Depart north" },
      { time: "11:30 AM", label: "Truro — 30 min charge + stretch" },
      { time: "1:00 PM", label: "Antigonish — lunch, ≈ 1 hr" },
      { time: "2:45 PM", label: "Aulds Cove — CHARGE TO 100%", detail: "Last fast charging before Cape Breton; then the Canso Causeway." },
      { time: "4:00 PM", label: "Arrive Baddeck — Telegraph House" },
      { time: "6:30 PM", label: "Dinner — Baddeck Lobster Suppers (go early)" },
      { time: "8:15 PM", label: "Sunset ≈ 8:15 PM ADT", detail: "Bras d'Or shore; stargaze if clear." },
      { time: "10:30 PM", label: "Bedtime (later if the sky delivers)" },
    ],
    memory: "The first sight of Bras d'Or Lake opening out beyond the causeway — an inland sea you didn't expect, and the calmest water of the whole trip.",
    map: [
      { label: "Lunenburg", lat: 44.38, lon: -64.31 },
      { label: "Truro", lat: 45.37, lon: -63.28 },
      { label: "Antigonish", lat: 45.62, lon: -61.99 },
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
    ],
  },
  {
    n: "08",
    date: "Friday · August 14, 2026",
    region: "Bell's lake & the Cabot Trail (west)",
    leg: "Baddeck → Alexander Graham Bell museum → Chéticamp",
    title: "Hydrofoils in the morning, the Skyline at dusk",
    subtitle: "Invention over Bras d'Or Lake, then up the western rampart of the Cabot Trail.",
    photo: NS_PHOTOS.bellMuseum,
    morningLocation: "Baddeck — a full charge and an unhurried morning on Bras d'Or before the museum opens.",
    breakfast: "The village; a second coffee on the water.",
    drive: "≈ 2 hr 30 min of actual driving spread across the day · 130 km to Chéticamp and the park's west gate — slow, and stopped often.",
    stops: [
      { name: "[Alexander Graham Bell museum](https://parks.canada.ca/lhn-nhs/ns/grahambell)", time: "1.5–2 hr", note: "The best small museum on the route. The telephone was only the start: the HD-4 hydrofoil that set a world marine-speed record in 1919; the Silver Dart and the first powered flight in the British Empire; his tetrahedral kites; and a lifetime of work on deafness and communication — all in a light-filled hall over the lake he chose for exactly this view. Engineering as romance, for Darren." },
      { name: "Chéticamp", time: "1 hr", note: "A proud Acadian fishing village — hooked-rug shops, a tall church, and the last full services before the park's west gate." },
      { name: "[Skyline Trail](https://parks.canada.ca/pn-np/ns/cbreton)", time: "1.5–2 hr", note: "The Trail's signature walk: a wide, mostly flat 7 km loop out to a headland boardwalk stepping down toward the Gulf. Moose common at dusk. Go for golden hour — or take the drive-up lookoffs for the view without the walk." },
    ],
    lunch: "Chéticamp — Acadian seafood at Le Gabriel or the Co-op's Restaurant Acadien; a bowl of fish fricot, with a look at the famous rug hooking.",
    afternoon: "The [Cabot Trail's](https://cabottrail.travel/) western switchbacks and lookoffs at French and MacKenzie Mountains, an early dinner, then the Skyline for sunset.",
    hotel: "[Cheticamp Outback Inn](https://www.cheticampoutbackinn.com) or [The Archie & Isidore Hotel](https://www.archieandisidore.ca) — small, exceptional-value village stays (both 9.6). Book direct now; Chéticamp sells out for August. Verified fallback: [Duck Cove Inn](https://www.duckcoveinn.ca) at Margaree Harbour.",
    dinner: "An early Acadian supper in Chéticamp before the Skyline; if there's a kitchen party or a fiddle session on, follow the sound afterward.",
    evening: "The Gulf sunset from the Skyline headland, where the sun drops straight into the sea.",
    charging: "No Superchargers on Cape Breton. You arrived on a full charge from Aulds Cove; use the inn's Level 2 and the Parks Canada fast charger at the Chéticamp Visitor Centre, and treat the Trail as a loop, not a dash. Plan it once and the whole day stays stress-free.",
    walking: "Skyline is easy–moderate (flat, exposed, 7 km round trip); the lookoffs are drive-up. You choose your effort. The museum is flat with lake-view terraces.",
    rainy: "The Bell museum is a superb rain plan on its own; the lookoffs and drive still deliver in cloud; save the Skyline for a clear evening.",
    sky: "Best chance for dark sky on the west of the Trail: Cape Breton Highlands has some of the darkest skies in Nova Scotia. If it's clear, the Gulf side after sunset is exceptional — no towns, no glow.",
    detailedPlan: [
      { time: "8:30 AM", label: "Breakfast on the water in Baddeck" },
      { time: "9:30 AM", label: "Alexander Graham Bell museum — ≈ 1.5–2 hr" },
      { time: "11:30 AM", label: "Drive the western Cabot Trail toward Chéticamp" },
      { time: "1:00 PM", label: "Arrive Chéticamp — check in (booked direct)" },
      { time: "1:30 PM", label: "Lunch — Le Gabriel / Restaurant Acadien" },
      { time: "3:00 PM", label: "French & MacKenzie Mountain lookoffs", detail: "Charge at the Parks Canada DCFC / inn L2." },
      { time: "5:30 PM", label: "Early Acadian dinner in Chéticamp" },
      { time: "6:45 PM", label: "Skyline Trail for golden hour — ≈ 2 hr" },
      { time: "8:22 PM", label: "Sunset ≈ 8:22 PM ADT", detail: "The sun into the Gulf; Milky Way after, if clear." },
      { time: "11:00 PM", label: "Bedtime" },
    ],
    memory: "Standing under the HD-4's hull in the morning, then the Skyline headland at golden hour that evening — the man who invented the telephone chose this lake, and by dusk you understand exactly why.",
    map: [
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
      { label: "Margaree", lat: 46.34, lon: -61.09 },
      { label: "Chéticamp", lat: 46.63, lon: -61.01 },
      { label: "Skyline Trail", lat: 46.75, lon: -60.86 },
    ],
  },
  {
    n: "09",
    date: "Saturday · August 15, 2026",
    region: "The Cabot Trail (east) & Ingonish",
    leg: "Chéticamp → Meat Cove → Ingonish",
    title: "The wild top of the island, and the darkest sky of all",
    subtitle: "Over the highlands to the rugged northern tip, then down the eastern coast to a warm sea and a sky full of stars.",
    photo: NS_PHOTOS.ingonish,
    morningLocation: "The western Highlands — coffee, then up and over the top of the park on the trip's most scenic single stretch.",
    breakfast: "The inn or a Pleasant Bay café before the mountain road.",
    drive: "≈ 3 hr of actual driving · 150 km with the Meat Cove detour — taken all day, because every bend is a lookoff (and the last few km to Meat Cove are gravel; take them slow).",
    stops: [
      { name: "Pleasant Bay", time: "30–45 min", note: "The whale-watching capital of the Trail — pilot whales are near-certain in season. Take a short morning look, or a full tour if you skip a longer stop elsewhere." },
      { name: "Meat Cove", time: "2 hr", note: "Added by request: the rugged northern tip of Cape Breton, reached by a committed detour (the last stretch is gravel). Sheer green headlands over open ocean, whales offshore, and the cliff-edge Chowder Hut for lunch — the wildest, most remote view of the whole trip." },
      { name: "Neil's Harbour", time: "30 min", note: "A working lighthouse and the Chowder House on the rocks — the best ice-cream-and-a-view stop on the island, on the way down to Ingonish." },
    ],
    lunch: "Meat Cove — chowder and a lobster roll at the cliff-edge Chowder Hut, ocean straight ahead; or Neil's Harbour if you skip the detour.",
    afternoon: "Back onto the Trail and down to Ingonish — the beach (freshwater on one side, warm salt on the other), the easy 4 km Middle Head headland walk, or just the sand. The sea here is genuinely swimmable in late summer.",
    hotel: "[Seascape Coastal Retreat](https://seascapecoastalretreat.com), Ingonish — oceanfront adults-only cottages with a hot tub (9.1), real character at about half a grand-resort price; Castle Rock Country Inn is the value alternative.",
    dinner: "Coastal Waters or the Main Street Restaurant & Bakery; or the Keltic Lodge's Purple Thistle if you'd like the grand dining room without the grand room rate. Sunset over Ingonish Bay.",
    evening: "The Highlands go pitch dark early — tonight is the one to stay up for.",
    charging: "No Superchargers on Cape Breton: use the Parks Canada fast charger at Ingonish Beach and destination charging in the village, and bring the car toward full here before you leave the Trail tomorrow. (Meat Cove has none — go with plenty of range.)",
    walking: "Easy–moderate — beaches and the flat Middle Head headland; Meat Cove's viewpoints involve short, steep gravel paths.",
    rainy: "Whale tours still sail in light rain; Neil's Harbour and its ice cream are cozy in fog; and the mountain road is glorious in drifting mist. Meat Cove's gravel road is best skipped in heavy rain.",
    sky: "The trip's marquee dark sky. Ingonish and the northern Highlands are the best bet of the whole route — if skies are clear, walk down to Ingonish Beach after dark for the Milky Way over the water, no light for miles.",
    detailedPlan: [
      { time: "8:30 AM", label: "Breakfast, then up over the top of the park" },
      { time: "10:15 AM", label: "Pleasant Bay — 30–45 min (or a whale tour)", detail: "Pick Meat Cove OR a long tour, not both, unless you start early." },
      { time: "12:00 PM", label: "Drive to Meat Cove", detail: "Last few km gravel — slow and steady." },
      { time: "12:45 PM", label: "Meat Cove — cliffs + Chowder Hut lunch, ≈ 2 hr" },
      { time: "3:30 PM", label: "Back to the Trail; Lone Shieling / Neil's Harbour", detail: "Ice cream at the Chowder House." },
      { time: "5:45 PM", label: "Arrive Ingonish — Seascape Coastal Retreat", detail: "Charge at Ingonish Beach DCFC." },
      { time: "7:00 PM", label: "Dinner — Coastal Waters / Main Street Bakery" },
      { time: "8:12 PM", label: "Sunset ≈ 8:12 PM ADT" },
      { time: "11:30 PM", label: "Ingonish Beach after dark — the best stars of the trip" },
    ],
    memory: "Chowder on a cliff at the wild top of the island by day, then lying on Ingonish Beach after dark under more stars than either of you had ever tried to count.",
    map: [
      { label: "Chéticamp", lat: 46.63, lon: -61.01 },
      { label: "Pleasant Bay", lat: 46.83, lon: -60.8 },
      { label: "Neil's Harbour", lat: 46.81, lon: -60.35 },
      { label: "Ingonish", lat: 46.68, lon: -60.39 },
    ],
  },
  {
    n: "10",
    date: "Sunday · August 16, 2026",
    region: "The long, kind reposition",
    leg: "Ingonish → the Annapolis Valley → Yarmouth",
    title: "Home starts turning west",
    subtitle: "The trip's second long drive — broken into a string of small, good reasons to stop, ending on the last Nova Scotia coast.",
    photo: NS_PHOTOS.capeForchu,
    morningLocation: "Ingonish — an early, unhurried start; the day is long on the map but never grim on the ground.",
    breakfast: "An Ingonish café; coffee to go and a plan for lunch.",
    drive: "≈ 7 hr moving · 640 km — off the island and down the western side of the province to Yarmouth. Long, but deliberately split with stops so it reads as a tour, not a haul. (Prefer gentler? Break it with a night in Wolfville or Annapolis Royal.)",
    stops: [
      { name: "Masstown Market", time: "45 min", note: "A beloved roadside institution near Truro — chowder, fresh bread, a lighthouse, and the best ice cream on the highway." },
      { name: "Annapolis Royal", time: "45 min", note: "Canada's oldest European settlement, the Historic Gardens, and Fort Anne's grassy earthworks over a tidal basin — a lovely leg-stretch on the Fundy shore." },
      { name: "[Cape Forchu Lightstation](https://www.novascotia.com/)", time: "1 hr", note: "The tapered 'apple-core' light on bare rock outside Yarmouth — the trip's last great Atlantic view, timed for sunset, with a café in the old keeper's house." },
    ],
    lunch: "Masstown Market — chowder and warm bread at a picnic table, then that ice cream for the road; or scallops if you dip down to Digby.",
    afternoon: "The easy 101 down the Fundy side of the valley, then out to Cape Forchu near Yarmouth for the evening light.",
    hotel: "[Comfort Inn Yarmouth](https://www.choicehotels.com) — the sensible pre-ferry sleep stop: free breakfast and parking, quiet, and five minutes from the CAT terminal. (Rodd Grand is the harbour-front alternative.)",
    dinner: "Yarmouth — Rudder's Seafood Restaurant & Brewpub on the harbour.",
    evening: "Sunset at Cape Forchu — the light, the rocks, the whole Atlantic going gold — the last, best Nova Scotia sundown before the crossing home.",
    charging: "A well-charged, well-fed long day: fast charging along the 104/102/101 at Port Hastings/Aulds Cove, Truro/Masstown, and New Minas; bring the car to full in Yarmouth tonight for the drive home after tomorrow's ferry.",
    walking: "Easy — a market, a garden, and a lighthouse point; the driving is the day's real effort, and it's shared and broken up.",
    rainy: "Masstown is indoor; Annapolis Royal's heritage streets and Cape Forchu's keeper's-house café shrug off rain; the drive is comfortable throughout.",
    sky: "A fine last dark sky: Cape Forchu and the coast southwest of Yarmouth are excellent. If it's clear, it's Atlantic on one side and stars on the other.",
    detailedPlan: [
      { time: "7:30 AM", label: "Early breakfast + depart Ingonish", detail: "Charge off the island via Baddeck / Aulds Cove." },
      { time: "11:00 AM", label: "Masstown Market — 45 min", detail: "Chowder + ice cream." },
      { time: "1:30 PM", label: "Annapolis Royal — 45 min–1 hr · lunch" },
      { time: "6:30 PM", label: "Arrive Yarmouth — Comfort Inn, quick check-in" },
      { time: "7:00 PM", label: "Dinner — Rudder's Brewpub" },
      { time: "7:45 PM", label: "Cape Forchu Lightstation for sunset — ≈ 1 hr" },
      { time: "8:15 PM", label: "Sunset ≈ 8:15 PM ADT", detail: "The last Nova Scotia sundown." },
      { time: "10:30 PM", label: "Charge full for tomorrow, then bed" },
    ],
    memory: "A market ice cream mid-drive, then the sun dropping behind the apple-core light at Cape Forchu — the trip's long day turned out to be one of its best.",
    map: [
      { label: "Ingonish", lat: 46.68, lon: -60.39 },
      { label: "Masstown", lat: 45.4, lon: -63.44 },
      { label: "Annapolis Royal", lat: 44.74, lon: -65.51 },
      { label: "Yarmouth", lat: 43.84, lon: -66.12 },
    ],
  },
  {
    n: "11",
    date: "Monday · August 17, 2026",
    region: "The ocean road home",
    leg: "Yarmouth, NS → (ferry) → Bar Harbor → Rockland, Maine",
    title: "Home by a different sea",
    subtitle: "A crossing of the Gulf of Maine, a relaxed afternoon in Acadia, and a quiet harbour-town finish.",
    photo: NS_PHOTOS.ferry,
    morningLocation: "Yarmouth — a calm morning; car-ferry check-in is simple and unhurried. (The CAT doesn't sail Tuesdays — today, a Monday, it runs.)",
    breakfast: "A Yarmouth café before boarding, then a second coffee on the open deck once you've cast off.",
    drive: "The 'drive' is the ≈ 3 hr 30 min sea crossing on [The CAT](https://www.ferries.ca/thecat) (Yarmouth 9:30 AM ADT → Bar Harbor ~12:00 PM EDT, booked), a relaxed Acadia afternoon, then ≈ 1 hr 50 min on to Rockland for the night.",
    stops: [
      { name: "The Gulf of Maine crossing", time: "3.5 hr", ferry: true, note: "Open water on a fast catamaran — watch for whales, porpoises, and shearwaters while Nova Scotia sinks quietly astern. This is the day's main event, and it's a good one." },
      { name: "[Acadia National Park](https://www.nps.gov/acad/) — a relaxed loop", time: "2.5 hr", note: "Sand Beach, Thunder Hole, and Jordan Pond for the century-old popovers on the lawn. Unhurried on purpose — Cadillac is deliberately skipped so the evening in Rockland stays calm (a daytime summit reservation is an optional add if you're ahead)." },
    ],
    lunch: "A lobster roll on the Bar Harbor pier once you land (Stewman's or Side Street Café) — take your time; there's no rush from here.",
    afternoon: "Acadia's Park Loop — Sand Beach, Thunder Hole, and popovers at Jordan Pond House — then charge at Ellsworth (right on the route) and drive on to Rockland by early evening.",
    hotel: "[Rockland Harbor Hotel](https://www.rocklandharborhotel.com) — central, walkable, free breakfast; a calmer, better-value finish than Bar Harbor, an hour closer to home, in a town with the coast's best food and the Farnsworth (Wyeth) museum.",
    dinner: "Rockland — Archer's on the Pier right on the water, or In Good Company / Cafe Miranda a block off it (reserve). Sunset over the harbour.",
    evening: "A golden-hour harbour walk before dinner, then an easy, low-key last night on the Maine coast.",
    charging: "Supercharge at Ellsworth (8 stalls, ~20 min from Bar Harbor and directly on the route to Rockland) — no detour; Level 2 at the hotel overnight to leave full for the drive home.",
    walking: "Easy — a deck, a pier, exactly as much of Acadia as you feel like, and a flat harbour-town stroll.",
    rainy: "The crossing sails rain or shine; Acadia is atmospheric in mist; and Rockland's Farnsworth museum and Main Street fill a wet evening beautifully.",
    sky: "An optional last look up on the drive west — but you'll have already had the best of it in Cape Breton.",
    detailedPlan: [
      { time: "8:00 AM ADT", label: "Ferry terminal check-in", detail: "Arrive 60–90 min early; have plate #, length & height." },
      { time: "9:30 AM ADT", label: "The CAT departs Yarmouth (booked)" },
      { time: "12:00 PM EDT", label: "Arrive Bar Harbor", detail: "Clocks back 1 hr; clear US customs." },
      { time: "12:30 PM", label: "Lobster-roll lunch on the pier" },
      { time: "1:30 PM", label: "Acadia — Sand Beach, Thunder Hole, Jordan Pond popovers" },
      { time: "4:00 PM", label: "Charge at Ellsworth Supercharger — ~20 min", detail: "On the route; no detour." },
      { time: "6:00 PM", label: "Arrive Rockland — Rockland Harbor Hotel", detail: "Harbour walk at golden hour." },
      { time: "7:15 PM", label: "Dinner — Archer's on the Pier (reserve)" },
      { time: "7:38 PM", label: "Sunset ≈ 7:38 PM EDT" },
      { time: "10:30 PM", label: "Bedtime" },
    ],
    memory: "Standing at the stern as Nova Scotia dissolved into the Gulf, popovers in Acadia by afternoon, and a quiet Rockland harbour dinner at sunset — the most elegant possible last chapter.",
    map: [
      { label: "Yarmouth", lat: 43.84, lon: -66.12 },
      { label: "Bar Harbor", lat: 44.39, lon: -68.2, ferry: true },
      { label: "Acadia", lat: 44.34, lon: -68.25 },
    ],
  },
  {
    n: "12",
    date: "Tuesday · August 18, 2026",
    region: "The closing chapter",
    leg: "Rockland, Maine → Salt Point, New York",
    title: "The long way home, on purpose",
    subtitle: "A leisurely breakfast, one last museum if you want it, then an easy road south — an hour shorter than it would have been.",
    photo: NS_PHOTOS.closing,
    morningLocation: "Rockland — a slow breakfast and a last look at the working waterfront before you point the car west.",
    breakfast: "Home Kitchen Café (Rockland's best brunch) or the Brass Compass; coffee from Rock City to go.",
    drive: "≈ 6 hr 45 min · 620 km to Salt Point — an hour shorter than leaving from Bar Harbor. Split it with a Portland stop, or run it in one gentle go.",
    stops: [
      { name: "Optional: Farnsworth Art Museum", time: "1–1.5 hr", note: "Right in downtown Rockland — the great Wyeth collection (N.C., Andrew, and Jamie). A perfect, unhurried last morning if you're interested; skip it and roll early if you'd rather." },
      { name: "Portland, Maine", time: "1 hr", note: "The midpoint break — one last Old Port stroll and a lobster roll, or oysters at Eventide, before the interstate south." },
    ],
    lunch: "Portland — a last lobster roll, or a browse and a bite in Freeport if you want one more stop.",
    afternoon: "The easy run south through New England; home to Salt Point by evening.",
    hotel: "Home — your own bed; twelve days of Atlantic behind you.",
    dinner: "Home, or a last coastal-Maine dinner if you split the drive — no wrong answer.",
    evening: "The driveway at Salt Point, the car ticking as it cools, already saying 'next year, the other one'.",
    charging: "A fully solved corridor — Superchargers at West Gardiner/Augusta (about an hour in), Kennebunk, Portsmouth, and Sturbridge. Leave Rockland full on the hotel's Level 2; the last day asks nothing of you.",
    walking: "None required — a driving day, kept deliberately humane.",
    rainy: "Nothing outdoors to protect; a rainy drive home is a gentle, unbothered way to land.",
    detailedPlan: [
      { time: "8:30 AM", label: "Leisurely breakfast — Home Kitchen Café" },
      { time: "10:00 AM", label: "Optional: Farnsworth Art Museum — ≈ 1–1.5 hr" },
      { time: "11:00 AM", label: "Depart for home", detail: "≈ 6 hr 45 min; charge at West Gardiner ~1 hr in." },
      { time: "12:30 PM", label: "Portland — lunch + Old Port stroll, ≈ 1 hr" },
      { time: "2:30 PM", label: "Portsmouth, NH — quick stretch (optional)" },
      { time: "6:30 PM", label: "Home — Salt Point, NY" },
      { time: "7:36 PM", label: "Sunset ≈ 7:36 PM (on the road / home)" },
    ],
    memory: "Pulling into Salt Point at dusk after a slow Rockland morning — the trip that was supposed to be the easy one, and turned out to be the one you'd keep talking about.",
    map: [
      { label: "Bar Harbor", lat: 44.39, lon: -68.2 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Salt Point", lat: 41.87, lon: -73.8 },
    ],
  },
];

/** Headline numbers for the "trip at a glance" band. */
export const NS_GLANCE: { k: string; v: string }[] = [
  { k: "12", v: "days · Aug 7–18, 2026" },
  { k: "1", v: "ocean crossing home" },
  { k: "6", v: "dark-sky chances" },
  { k: "2", v: "longer drives — the rest are short" },
];

/** The three-beat route summary for the map section. */
export const NS_ROUTE_NOTES: { k: string; v: string }[] = [
  { k: "Out", v: "Up the Maine coast to Bangor, then a soft road-crossing at Calais — no ferry to make on the way north." },
  { k: "Around", v: "A relaxed loop: Fundy, the Valley, Halifax, the South Shore, and the Cabot Trail — value inns, not luxury, unhurried the whole way." },
  { k: "Home", v: "The Yarmouth ferry across the Gulf of Maine to Bar Harbor, a relaxed Acadia afternoon, and a last night at Rockland — home by a different sea than you left on." },
];
