import type { TripDay } from "@/lib/trip-types";
import { NS_PHOTOS } from "./photos";

/**
 * NOVA SCOTIA — THE JOURNEY, DAY BY DAY
 * -------------------------------------
 * A relaxed 12-day 2026 road trip for Darren & Melissa: north up the Maine
 * coast, a soft road-crossing into Canada, a gentle loop around Nova Scotia to
 * Cape Breton and the Cabot Trail, and home across the Gulf of Maine by ferry.
 *
 * Dates are fixed around the Yarmouth → Bar Harbor ferry on Monday, August 17,
 * 2026 (the CAT does not sail Tuesdays), which sets departure on Friday,
 * August 7 and the drive home on Tuesday, August 18.
 *
 * Written warmer and easier than the Newfoundland expedition — comfort,
 * specifics, and reassurance for Melissa; scenic drives, hidden gems, food,
 * engineering, photography, and dark skies for Darren. Restaurants, inns,
 * wineries, parks, and the ferry are linked with [label](url) — verify hours
 * and book ahead before the trip; timings and distances are honest estimates.
 */

export const NS_DAYS: TripDay[] = [
  {
    n: "01",
    date: "Friday · August 7, 2026",
    region: "The gentle launch",
    leg: "Salt Point, NY → Portland, Maine",
    title: "North, without the alarm clock",
    subtitle: "No ferry to catch, no dark start — just the coast of Maine by dinner.",
    photo: NS_PHOTOS.portland,
    morningLocation: "Home in Salt Point, at a civilized hour — coffee on the porch, the car already packed.",
    breakfast: "Something quick at home, or a pastry from the village. The real eating starts tonight.",
    drive: "≈ 5 hr 15 min · 500 km — Taconic to the Mass Pike, then I-95 to the Maine coast. All highway, all easy.",
    stops: [
      { name: "[[map|Portsmouth, New Hampshire]]", time: "45 min", note: "A stretch and a harbour walk where New England first smells like the sea." },
      { name: "[[map|Portland Head Light, Cape Elizabeth|Portland Head Light, Cape Elizabeth, Maine]]", time: "45 min", note: "The most photographed lighthouse in Maine, right on the way in — a soft first postcard for Darren's camera." },
    ],
    lunch: "On the road — a lobster roll in Portsmouth, or hold out for oysters in Portland.",
    afternoon: "Into Portland's Old Port — cobblestones, chandleries, and the Eastern Promenade path along Casco Bay.",
    hotel: "[The Press Hotel](https://www.thepresshotel.com/)[[dir|The Press Hotel, Portland, Maine]] (Autograph Collection) — walkable to everything, quietly design-forward.",
    dinner: "[Eventide Oyster Co.](https://www.eventideoysterco.com/)[[dir|Eventide Oyster Co., Portland, Maine]] for the brown-butter lobster bun and cold local oysters; [Fore Street](https://www.forestreet.biz/)[[dir|Fore Street, Portland, Maine]] if you want a proper room and a wood fire.",
    evening: "A slow walk along the working waterfront; the light on Casco Bay, boats coming in.",
    charging: "Superchargers all down I-95 (Sturbridge, Auburn) and several in Portland — charge over dinner, Level 2 at the hotel overnight. Nothing to plan.",
    walking: "Easy — town strolls only.",
    rainy: "The Portland Museum of Art (Homer and the Wyeths) or the covered Public Market. A rainy first evening is no loss here.",
    memory: "The first oysters and a lobster roll with the Atlantic finally in the frame — and not one thing about the day that felt hard.",
    map: [
      { label: "Salt Point", lat: 41.87, lon: -73.8 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
    ],
  },
  {
    n: "02",
    date: "Saturday · August 8, 2026",
    region: "Into Canada, softly",
    leg: "Portland, Maine → St. Andrews by-the-Sea, New Brunswick",
    title: "The border you barely feel",
    subtitle: "Up the Maine coast, across at Calais, into the gentlest town in Canada.",
    photo: NS_PHOTOS.standrews,
    morningLocation: "Portland — an unhurried breakfast and one more look at the harbour before you point the car northeast.",
    breakfast: "[[map|Standard Baking Co.|Standard Baking Co., Portland, Maine]] pastries, or the hotel. Grab a coffee for the coast road.",
    drive: "≈ 4 hr 45 min · 400 km — US-1 up the Bold Coast, over the border at Calais / St. Stephen. The road empties and slows the whole way.",
    stops: [
      { name: "[[map|Wiscasset, Maine]]", time: "45 min", note: "The lobster-roll pilgrimage — Red's Eats or Sprague's, eaten at a picnic table by the river." },
      { name: "[[map|St. Stephen, New Brunswick]]", time: "45 min", note: "The Ganong chocolate town, right at the border — the Chocolate Museum and a bag of chicken-bone candy for the road." },
    ],
    lunch: "Wiscasset — the classic Maine lobster roll, hot butter or cold mayo, your call.",
    afternoon: "Cross into Canada (passports ready; the crossing here is calm and quick), then the short hop to St. Andrews — Kingsbrae Garden or the long wharf on Passamaquoddy Bay.",
    hotel: "[The Algonquin Resort](https://algonquinresort.com/)[[dir|The Algonquin Resort, St. Andrews, New Brunswick]] — a grand seaside Tudor with EV charging; or a small inn in town.",
    dinner: "[Rossmount Inn](https://www.rossmountinn.com/)[[dir|Rossmount Inn, St. Andrews, New Brunswick]], one of the Maritimes' best tables, or the [[map|Niger Reef Tea House|Niger Reef Tea House, St. Andrews, New Brunswick]] on the water.",
    evening: "Sunset from the wharf; whales sometimes roll through the bay off the point.",
    charging: "Top up in Augusta before the coast road; Canadian charging begins around St. Stephen and Saint John. Level 2 at the Algonquin overnight — arrive relaxed, not hunting for a plug.",
    walking: "Easy — gardens and a flat seaside town.",
    rainy: "Kingsbrae Garden's pavilions, the Ganong Chocolate Museum, or the Huntsman Fundy Discovery Aquarium.",
    sky: "If skies are clear, the wharf gives your first real spread of stars — light pollution thins the moment you leave the I-95 corridor. An easy, optional first look up.",
    memory: "Crossing into Canada and feeling the whole trip downshift — chocolate in hand, whales in the bay, and nowhere you had to be.",
    map: [
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Wiscasset", lat: 44.0, lon: -69.66 },
      { label: "St. Stephen", lat: 45.19, lon: -67.28 },
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
    ],
  },
  {
    n: "03",
    date: "Sunday · August 9, 2026",
    region: "The highest tides on earth",
    leg: "St. Andrews → Hopewell Rocks & the Bay of Fundy",
    title: "Walk the floor of the ocean",
    subtitle: "Time the day to the tide, and stand where the sea will be.",
    photo: NS_PHOTOS.fundy,
    morningLocation: "St. Andrews — a good breakfast, then east along the Fundy shore (check today's low-tide time first; the whole day pivots on it).",
    breakfast: "The Algonquin's dining room, or [[map|Honeybeans|Honeybeans, St. Andrews, New Brunswick]] in town.",
    drive: "≈ 3 hr 15 min · 260 km to Hopewell, plus the Fundy park loop — an easy day of short hops between big views.",
    stops: [
      { name: "[[map|Saint John, NB|Saint John, New Brunswick]]", time: "1 hr", note: "The uptown red-brick core and the Reversing Falls, where the Fundy tide runs the river backwards." },
      { name: "[Hopewell Rocks](https://www.thehopewellrocks.ca/)[[dir|Hopewell Rocks Provincial Park, New Brunswick]]", time: "1.5–2 hr", note: "Descend the stairs to the actual sea floor at low tide and walk among tree-topped flowerpot stacks carved by forty vertical feet of tide." },
    ],
    lunch: "Alma — lobster and chowder at the [[map|Tides|Tides Restaurant, Alma, New Brunswick]], and a [[map|Kelly's|Kelly's Bake Shop, Alma, New Brunswick]] sticky bun the size of your hand.",
    afternoon: "Hopewell Rocks at low tide, then Cape Enrage's cliffs; the sea floor you walked at noon is under three storeys of water by dusk.",
    hotel: "A Fundy-shore inn near Alma / Hopewell (the [[map|Broadleaf|Broadleaf Guest Ranch, Hopewell Hill, New Brunswick]], or the [[map|Parkland Village Inn|Parkland Village Inn, Alma, New Brunswick]]), or into Moncton for more choice.",
    dinner: "Fundy scallops and Alma lobster, a local ale, the tide coming in outside the window.",
    evening: "Back to the flats at dusk to watch the water swallow the ground you stood on — the same view, twice, transformed.",
    charging: "Superchargers in Saint John and Moncton, both near food. Alma is remote — arrive with a good charge and top up before the park.",
    walking: "Easy–moderate — stairs down to the ocean floor at Hopewell; flat clifftop paths at Cape Enrage.",
    rainy: "The tide performs in any weather; the Hopewell interpretive centre and Cape Enrage's café keep you dry between shows.",
    sky: "Best chance yet: Fundy National Park is a certified Dark Sky Preserve. If it's clear and you've stayed outside Moncton, this is the trip's first great dark sky — the Milky Way over the bay, no city glow.",
    memory: "Standing on the ocean floor at noon, then watching four storeys of tide quietly erase it by dark.",
    map: [
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
      { label: "Saint John", lat: 45.27, lon: -66.06 },
      { label: "Hopewell Rocks", lat: 45.82, lon: -64.58 },
      { label: "Alma", lat: 45.6, lon: -64.95 },
    ],
  },
  {
    n: "04",
    date: "Monday · August 10, 2026",
    region: "Across into Nova Scotia",
    leg: "Bay of Fundy → Wolfville & Grand-Pré → Halifax",
    title: "Wine country by the world's biggest tide",
    subtitle: "Cross into Nova Scotia through orchards and dykelands; arrive in Halifax by dark.",
    photo: NS_PHOTOS.wolfville,
    morningLocation: "The Fundy shore — a slow start; the drive into Nova Scotia over the Tantramar marshes is flat and painless.",
    breakfast: "The inn, or a last Alma sticky bun for the road.",
    drive: "≈ 3 hr to Wolfville, then 1 hr on to Halifax · 330 km total — over the isthmus at Amherst into Nova Scotia.",
    stops: [
      { name: "[[map|Grand-Pré National Historic Site|Grand-Pré National Historic Site, Nova Scotia]]", time: "1 hr", note: "A UNESCO landscape of Acadian dykelands and the moving story of the 1755 deportation — quiet, beautiful, and grounding." },
      { name: "[[map|Wolfville wineries|Wolfville, Nova Scotia]]", time: "1.5–2 hr", note: "[Lightfoot & Wolfville](https://www.lightfootandwolfville.com/)[[dir|Lightfoot & Wolfville, Wolfville, Nova Scotia]] or [Domaine de Grand Pré](https://www.grandprewines.com/)[[dir|Domaine de Grand Pré, Wolfville, Nova Scotia]] — Nova Scotia's crisp Tidal Bay whites, tasted on a patio above the flats." },
    ],
    lunch: "Le Caveau at [Domaine de Grand Pré](https://www.grandprewines.com/)[[dir|Domaine de Grand Pré, Wolfville, Nova Scotia]], or the [Lightfoot & Wolfville](https://www.lightfootandwolfville.com/)[[dir|Lightfoot & Wolfville, Wolfville, Nova Scotia]] terrace — valley-to-table with the Bay of Fundy shining below.",
    afternoon: "Walk the Grand-Pré dykelands, then the genuinely easy hour into Halifax — the biggest city of the trip arrives gently.",
    hotel: "Halifax — the [Muir](https://www.muirhotel.com/)[[dir|Muir Hotel, Halifax, Nova Scotia]] (Autograph Collection) right on the waterfront, or the classic [[map|Halliburton|The Halliburton, Halifax, Nova Scotia]] in the old town.",
    dinner: "[The Bicycle Thief](https://bicyclethief.ca/)[[dir|The Bicycle Thief, Halifax, Nova Scotia]] on the boardwalk; [Bar Kismet](https://www.barkismet.com/)[[dir|Bar Kismet, Halifax, Nova Scotia]] if you want the local chefs' favourite.",
    evening: "The Halifax waterfront after dark — schooners, buskers, harbour lights, and the longest downtown boardwalk in the world underfoot.",
    charging: "Supercharge in Truro at the midpoint and at several Halifax locations; Level 2 at the hotel overnight.",
    walking: "Easy — vineyard rows and a flat historic site.",
    rainy: "Tastings are indoors; Grand-Pré's interpretive centre is excellent; and Halifax is a city built for a rainy evening.",
    memory: "A glass of Tidal Bay on a vineyard patio, the Bay of Fundy shining below — the moment Nova Scotia stopped being a plan and started being the trip.",
    map: [
      { label: "Alma", lat: 45.6, lon: -64.95 },
      { label: "Amherst", lat: 45.83, lon: -64.21 },
      { label: "Wolfville", lat: 45.09, lon: -64.36 },
      { label: "Halifax", lat: 44.65, lon: -63.57 },
    ],
  },
  {
    n: "05",
    date: "Tuesday · August 11, 2026",
    region: "Halifax, at ease",
    leg: "Halifax — a day out of the car",
    title: "A city that feels like a coastal town",
    subtitle: "Waterfront, Citadel, a museum with a Titanic story — and no driving at all.",
    photo: NS_PHOTOS.halifax,
    morningLocation: "Halifax — coffee on the waterfront; today the car doesn't move and neither do you, faster than you want to.",
    breakfast: "The [[map|Seaport Farmers' Market|Halifax Seaport Farmers' Market, Halifax, Nova Scotia]] (North America's oldest) for coffee and pastries among the stalls.",
    drive: "None to speak of — this is the day that proves the trip isn't all windshield.",
    stops: [
      { name: "[Halifax Citadel](https://parks.canada.ca/lhn-nhs/ns/halifax)[[dir|Halifax Citadel National Historic Site, Halifax, Nova Scotia]]", time: "1.5 hr", note: "The star-shaped hilltop fort, the noon gun, kilted guards, and the whole harbour laid out below." },
      { name: "[Maritime Museum of the Atlantic](https://maritimemuseum.novascotia.ca/)[[dir|Maritime Museum of the Atlantic, Halifax, Nova Scotia]]", time: "1.5 hr", note: "The definitive Titanic collection and the story of the 1917 Halifax Explosion — history and engineering in one waterfront hall for Darren." },
      { name: "[[map|Halifax Public Gardens|Halifax Public Gardens, Halifax, Nova Scotia]]", time: "45 min", note: "Formal Victorian gardens, a bandstand, and a bench in the shade — the softest possible city stop." },
    ],
    lunch: "A lobster roll on the boardwalk, or the Battered Fish; keep it light and outdoors.",
    afternoon: "Take the Dartmouth ferry across the harbour and back — the oldest saltwater ferry in North America and, at a few dollars, the best harbour cruise there is.",
    hotel: "Same Halifax hotel — no repacking, no logistics, just a second easy night.",
    dinner: "[Bar Kismet](https://www.barkismet.com/)[[dir|Bar Kismet, Halifax, Nova Scotia]] (a seafood tasting) or the [[map|Stubborn Goat|The Stubborn Goat Gastropub, Halifax, Nova Scotia]] gastropub — then live East Coast fiddle at [[map|The Carleton|The Carleton, Halifax, Nova Scotia]].",
    evening: "A pint and a tune at The Carleton or the Lower Deck — the real Maritime warmth, no cover charge on the feeling.",
    charging: "The car rests all day on the hotel's Level 2 — genuinely nothing to think about.",
    walking: "Easy — city strolling entirely at your own pace.",
    rainy: "Everything today has a roof — the museums, the market, the fiddle. A rainy Halifax day is a good day by design.",
    memory: "The harbour ferry at dusk, the city gold behind you, realizing you hadn't touched the car in a full day and hadn't missed it once.",
    map: [
      { label: "Halifax", lat: 44.65, lon: -63.57 },
      { label: "Dartmouth", lat: 44.67, lon: -63.57 },
    ],
  },
  {
    n: "06",
    date: "Wednesday · August 12, 2026",
    region: "The South Shore",
    leg: "Halifax → Peggy's Cove → Mahone Bay → Lunenburg",
    title: "Lighthouses, three churches, and a painted town",
    subtitle: "The classic coast — photographed early, tasted slowly.",
    photo: NS_PHOTOS.peggys,
    morningLocation: "Halifax — an early start out along St. Margarets Bay, ahead of the tour buses, to have Peggy's Cove to yourselves.",
    breakfast: "Grab-and-go from Halifax; a proper brunch waits in Mahone Bay.",
    drive: "≈ 2 hr 30 min total across the whole day · 150 km — short, scenic legs with long stops between.",
    stops: [
      { name: "[[map|Peggy's Cove|Peggy's Cove, Nova Scotia]]", time: "1–1.5 hr", note: "The red-capped light on wave-worn granite. Go early for the low light, the quiet, and the safe new viewing deck — mind the wet black rock." },
      { name: "[[map|Mahone Bay|Mahone Bay, Nova Scotia]]", time: "1 hr", note: "The three steepled churches mirrored in a calm bay, and a main street of makers, bakers, and a very good kouign-amann." },
    ],
    lunch: "Mahone Bay — [[map|Oh My Cod|Oh My Cod, Mahone Bay, Nova Scotia]] or [[map|Rebecca's|Rebecca's Restaurant, Mahone Bay, Nova Scotia]]; a pastry and a coffee by the water.",
    afternoon: "Lunenburg's UNESCO Old Town — the boldly painted waterfront, the Fisheries Museum, the Bluenose II if she's in port, and a wander up the coloured streets.",
    hotel: "Lunenburg — the [Mecklenburgh Inn](https://www.mecklenburghinn.ca/)[[dir|Mecklenburgh Inn, Lunenburg, Nova Scotia]] or the [[map|Lunenburg Arms|Lunenburg Arms Hotel, Lunenburg, Nova Scotia]], right in the old town.",
    dinner: "Lunenburg — the [[map|Half Shell|The Half Shell, Lunenburg, Nova Scotia]] for oysters, the [Salt Shaker Deli](https://www.saltshakerdeli.com/)[[dir|Salt Shaker Deli, Lunenburg, Nova Scotia]] harbourside, or [[map|Bar Salvador|Bar Salvador, Lunenburg, Nova Scotia]] for something livelier.",
    evening: "The waterfront at blue hour — dories, rigging, and reflections; a nightcap on an inn porch.",
    charging: "Supercharge in Bridgewater (ten minutes from Lunenburg) or back in Halifax; a short-mileage day makes charging an afterthought.",
    walking: "Easy — Peggy's granite is uneven and slick when wet; the towns themselves are flat and gentle.",
    rainy: "The Fisheries Museum of the Atlantic is a superb indoor half-day; Ironworks Distillery for a tasting; and Peggy's Cove is at its most dramatic in fog.",
    sky: "Optional and photogenic rather than dark: if the harbour's clear, the Lunenburg waterfront scatters soft stars over the rigging — not the trip's darkest sky, but its prettiest for a long exposure.",
    memory: "Peggy's Cove almost to yourselves at first light, then a slow lobster supper on the Lunenburg waterfront — the two most photographed places on the coast, both unhurried.",
    map: [
      { label: "Halifax", lat: 44.65, lon: -63.57 },
      { label: "Peggy's Cove", lat: 44.49, lon: -63.92 },
      { label: "Mahone Bay", lat: 44.45, lon: -64.38 },
      { label: "Lunenburg", lat: 44.38, lon: -64.31 },
    ],
  },
  {
    n: "07",
    date: "Thursday · August 13, 2026",
    region: "Toward Cape Breton",
    leg: "Lunenburg → Baddeck, Cape Breton",
    title: "The long, easy reach to the inland sea",
    subtitle: "A scenic repositioning day that ends on the shore of Bras d'Or Lake.",
    photo: NS_PHOTOS.brasdor,
    morningLocation: "Lunenburg — a last harbour coffee, then north; the day is about arriving somewhere serene, not rushing.",
    breakfast: "A Lunenburg café; pastries and a flat white for the road.",
    drive: "≈ 4 hr 30 min · 430 km — up through the province and over the Canso Causeway onto Cape Breton, broken by good stops.",
    stops: [
      { name: "[[map|Truro|Truro, Nova Scotia]]", time: "30 min", note: "A charge and a leg-stretch; if the tide's right, catch the Salmon River tidal bore rolling upstream." },
      { name: "[[map|Antigonish|Antigonish, Nova Scotia]]", time: "1 hr", note: "A pretty university town for a relaxed main-street lunch — the last real town before the island." },
      { name: "[[map|Canso Causeway|Canso Causeway, Nova Scotia]]", time: "15 min", note: "Cross the deepest causeway in the world onto Cape Breton; the road opens and the light changes." },
    ],
    lunch: "Antigonish — a bistro on Main Street; unhurried, good coffee, no rush to the car.",
    afternoon: "Over the causeway and along the shore of Bras d'Or Lake — a vast inland sea — into Baddeck by late afternoon.",
    hotel: "Baddeck — the [[map|Inverary Resort|Inverary Resort, Baddeck, Nova Scotia]] on the lake, or the [[map|Water's Edge Inn|Water's Edge Inn, Baddeck, Nova Scotia]] in the village.",
    dinner: "Baddeck — the [[map|Bell Buoy|The Bell Buoy Restaurant, Baddeck, Nova Scotia]], or the community tradition of [Baddeck Lobster Suppers](https://baddecklobstersuppers.ca/)[[dir|Baddeck Lobster Suppers, Baddeck, Nova Scotia]] (all-you-can-eat mussels and chowder before the lobster).",
    evening: "The Bras d'Or shore at dusk — glass-calm water, loons calling, the quietest night of the trip so far.",
    charging: "Supercharge in Truro and near New Glasgow / Port Hastings on the way; Baddeck has reliable destination charging. Top up here — this is your staging point for the Cabot Trail.",
    walking: "Easy — a stretch-your-legs travel day.",
    rainy: "The drive is the day and it's comfortable in any weather; if it pours, the [Bell museum](https://parks.canada.ca/lhn-nhs/ns/grahambell) tomorrow is entirely indoors.",
    sky: "Best chance for dark sky tonight: away from the village, the Bras d'Or shore is genuinely dark. If it's clear, step out after dinner — the lake doubles every star.",
    memory: "The first sight of Bras d'Or Lake opening out beyond the causeway — an inland sea you didn't expect, and the calmest water of the whole trip.",
    map: [
      { label: "Lunenburg", lat: 44.38, lon: -64.31 },
      { label: "Truro", lat: 45.37, lon: -63.28 },
      { label: "Antigonish", lat: 45.62, lon: -61.99 },
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
    ],
  },
  {
    n: "08",
    date: "Friday · August 14, 2026",
    region: "Bell's lake & the Cabot Trail (west)",
    leg: "Baddeck → Alexander Graham Bell museum → Chéticamp",
    title: "Hydrofoils in the morning, the Skyline at dusk",
    subtitle: "Invention over Bras d'Or Lake, then up the western rampart of the Cabot Trail.",
    photo: NS_PHOTOS.bellMuseum,
    morningLocation: "Baddeck — a full charge and an unhurried morning on Bras d'Or before the museum opens.",
    breakfast: "The inn, on the water; a second coffee on the dock.",
    drive: "≈ 2 hr 30 min of actual driving spread across the day · 130 km to Chéticamp and the park's west gate — slow, and stopped often.",
    stops: [
      { name: "[Alexander Graham Bell museum](https://parks.canada.ca/lhn-nhs/ns/grahambell)[[dir|Alexander Graham Bell National Historic Site, Baddeck, Nova Scotia]]", time: "1.5–2 hr", note: "The best small museum on the route. The telephone was only the start: the HD-4 hydrofoil that set a world marine-speed record in 1919; the Silver Dart and the first powered flight in the British Empire; his tetrahedral kites; and a lifetime of work on deafness and communication — all in a light-filled hall over the lake he chose for exactly this view. Engineering as romance, for Darren." },
      { name: "[[map|Chéticamp|Chéticamp, Nova Scotia]]", time: "1 hr", note: "A proud Acadian fishing village — hooked-rug shops, a tall church, and the last full services before the park's west gate." },
      { name: "[Skyline Trail](https://parks.canada.ca/pn-np/ns/cbreton)[[dir|Skyline Trail, Cape Breton Highlands National Park, Nova Scotia]]", time: "1.5–2 hr", note: "The Trail's signature walk: a wide, mostly flat 7 km loop out to a headland boardwalk stepping down toward the Gulf. Moose common at dusk. Go for golden hour — or take the drive-up lookoffs for the view without the walk." },
    ],
    lunch: "Chéticamp — Acadian seafood; a bowl of fish fricot or fresh haddock, with a look at the famous rug hooking.",
    afternoon: "The [Cabot Trail's](https://cabottrail.travel/) western switchbacks and lookoffs at French and MacKenzie Mountains, then the Skyline for sunset.",
    hotel: "Chéticamp or a Pleasant Bay inn inside the park's reach — small, simple, and perfectly placed for the dark.",
    dinner: "Chéticamp — an Acadian supper; if there's a kitchen party or a fiddle session on, follow the sound.",
    evening: "The Gulf sunset from the western shore, where the sun drops straight into the sea.",
    charging: "Plan this stretch once: leave Baddeck at 100%, use Chéticamp's Level 2, and treat the Trail as a loop, not a dash. Think ahead here and the whole day stays stress-free — Cape Breton's chargers are few and far between.",
    walking: "Skyline is easy–moderate (flat, exposed, 7 km round trip); the lookoffs are drive-up. You choose your effort. The museum is flat with lake-view terraces.",
    rainy: "The Bell museum is a superb rain plan on its own; the lookoffs and drive still deliver in cloud; save the Skyline for a clear evening.",
    sky: "Best chance for dark sky on the west of the Trail: Cape Breton Highlands has some of the darkest skies in Nova Scotia. If it's clear, the Gulf side after sunset is exceptional — no towns, no glow.",
    memory: "Standing under the HD-4's hull in the morning, then the Skyline headland at golden hour that evening — the man who invented the telephone chose this lake, and by dusk you understand exactly why.",
    map: [
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
      { label: "Margaree", lat: 46.34, lon: -61.09 },
      { label: "Chéticamp", lat: 46.63, lon: -61.01 },
      { label: "Skyline Trail", lat: 46.75, lon: -60.86 },
    ],
  },
  {
    n: "09",
    date: "Saturday · August 15, 2026",
    region: "The Cabot Trail (east) & Ingonish",
    leg: "Chéticamp → Pleasant Bay → Ingonish",
    title: "Down the eastern coast, slowly",
    subtitle: "Beaches instead of cliffs to climb, a warm sea, and the darkest sky of all.",
    photo: NS_PHOTOS.ingonish,
    morningLocation: "The western Highlands — coffee, then up and over the top of the park on the trip's most scenic single stretch.",
    breakfast: "The inn or a Pleasant Bay café before the mountain road.",
    drive: "≈ 2 hr 30 min of actual driving · 110 km — taken all day, because every bend is a lookoff.",
    stops: [
      { name: "[[map|Pleasant Bay|Pleasant Bay, Nova Scotia]]", time: "30 min – 2 hr", note: "The whale-watching capital of the Trail — pilot whales are near-certain in season; or just the little harbour and a chowder." },
      { name: "[[map|Lone Shieling|Lone Shieling, Cape Breton Highlands National Park, Nova Scotia]]", time: "20 min", note: "A short, flat loop through a rare stand of 350-year-old sugar maples — an easy leg-stretch in deep green quiet." },
      { name: "[[map|Neil's Harbour|Neil's Harbour, Nova Scotia]]", time: "30 min", note: "A working lighthouse and the Chowder House on the rocks — the best ice-cream-and-a-view stop on the island." },
    ],
    lunch: "Neil's Harbour — the [[map|Chowder House|Chowder House, Neil's Harbour, Nova Scotia]] by the lighthouse, seafood chowder on a picnic table over the water.",
    afternoon: "Ingonish — the beach (freshwater on one side, warm salt on the other), the easy 4 km Middle Head headland walk, or just the sand. The sea here is genuinely swimmable in late summer.",
    hotel: "[The Keltic Lodge at the Highlands](https://kelticlodge.ca/)[[dir|Keltic Lodge, Ingonish Beach, Nova Scotia]], on Middle Head above the sea — the grand resort of the Trail; or a quieter Ingonish inn.",
    dinner: "[The Keltic Lodge](https://kelticlodge.ca/)[[dir|Keltic Lodge, Ingonish Beach, Nova Scotia]] (the Purple Thistle dining room) or a local seafood shack, sunset over Ingonish Bay.",
    evening: "The Highlands go pitch dark early — tonight is the one to stay up for.",
    charging: "Ingonish has destination charging (the Keltic Lodge and village); bring it to full here before you leave the Trail tomorrow.",
    walking: "Easy — beaches and the flat Middle Head headland; the whale boat does the rest of the work.",
    rainy: "Whale tours still sail in light rain; Neil's Harbour and its ice cream are cozy in fog; and the mountain road is glorious in drifting mist.",
    sky: "The trip's marquee dark sky. Ingonish and the northern Highlands are the best bet of the whole route — if skies are clear, walk down to Ingonish Beach after dark for the Milky Way over the water, no light for miles.",
    memory: "Floating in a warm Ingonish sea in the afternoon, then lying on the same beach after dark under more stars than either of you had ever tried to count.",
    map: [
      { label: "Chéticamp", lat: 46.63, lon: -61.01 },
      { label: "Pleasant Bay", lat: 46.83, lon: -60.8 },
      { label: "Neil's Harbour", lat: 46.81, lon: -60.35 },
      { label: "Ingonish", lat: 46.68, lon: -60.39 },
    ],
  },
  {
    n: "10",
    date: "Sunday · August 16, 2026",
    region: "The long, kind reposition",
    leg: "Ingonish → the Annapolis Valley → Yarmouth",
    title: "Home starts turning west",
    subtitle: "The trip's one real drive — broken into a string of small, good reasons to stop, ending on the last Nova Scotia coast.",
    photo: NS_PHOTOS.capeForchu,
    morningLocation: "Ingonish — an early, unhurried start; the day is long on the map but never grim on the ground.",
    breakfast: "[The Keltic Lodge](https://kelticlodge.ca/)[[dir|Keltic Lodge, Ingonish Beach, Nova Scotia]] or an Ingonish café; coffee to go and a plan for lunch.",
    drive: "≈ 7 hr moving · 640 km — off the island and down the western side of the province to Yarmouth. Long, but deliberately split with stops so it reads as a tour, not a haul. (Prefer gentler? Break it with a night in Wolfville or Annapolis Royal.)",
    stops: [
      { name: "[[map|Masstown Market|Masstown Market, Nova Scotia]]", time: "45 min", note: "A beloved roadside institution near Truro — chowder, fresh bread, a lighthouse, and the best ice cream on the highway." },
      { name: "[[map|Annapolis Royal|Annapolis Royal, Nova Scotia]]", time: "45 min", note: "Canada's oldest European settlement, the Historic Gardens, and Fort Anne's grassy earthworks over a tidal basin — a lovely leg-stretch on the Fundy shore." },
      { name: "[Cape Forchu Lightstation](https://www.novascotia.com/)[[dir|Cape Forchu Lightstation, Yarmouth, Nova Scotia]]", time: "1 hr", note: "The tapered 'apple-core' light on bare rock outside Yarmouth — the trip's last great Atlantic view, timed for sunset, with a café in the old keeper's house." },
    ],
    lunch: "Masstown Market — chowder and warm bread at a picnic table, then that ice cream for the road; or scallops if you dip down to Digby.",
    afternoon: "The easy 101 down the Fundy side of the valley, then out to Cape Forchu near Yarmouth for the evening light.",
    hotel: "Yarmouth — the [[map|Rodd Grand|Rodd Grand Yarmouth, Yarmouth, Nova Scotia]] on the harbour; or, for the splurge and the stars, [Trout Point Lodge](https://www.troutpoint.com/)[[dir|Trout Point Lodge, East Kemptville, Nova Scotia]] inland (a certified dark-sky destination — see tonight's sky).",
    dinner: "Yarmouth — [[map|Rudder's Brew Pub|Rudder's Seafood Restaurant and Brew Pub, Yarmouth, Nova Scotia]] on the harbour, or the [Trout Point Lodge](https://www.troutpoint.com/)[[dir|Trout Point Lodge, East Kemptville, Nova Scotia]] dining room if you've gone inland.",
    evening: "Sunset at Cape Forchu — the light, the rocks, the whole Atlantic going gold — the last, best Nova Scotia sundown before the crossing home.",
    charging: "A well-charged, well-fed long day: fast charging along the 104/102/101 at Port Hastings, Truro/Masstown, and New Minas; bring the car to full in Yarmouth tonight for the drive home after tomorrow's ferry.",
    walking: "Easy — a market, a garden, and a lighthouse point; the driving is the day's real effort, and it's shared and broken up.",
    rainy: "Masstown is indoor; Annapolis Royal's heritage streets and Cape Forchu's keeper's-house café shrug off rain; the drive is comfortable throughout.",
    sky: "A fine last dark sky: Cape Forchu and the coast southwest of Yarmouth are excellent, and [Trout Point Lodge](https://www.troutpoint.com/) nearby is a certified dark-sky destination. If it's clear, it's Atlantic on one side and stars on the other.",
    memory: "A market ice cream mid-drive, then the sun dropping behind the apple-core light at Cape Forchu — the trip's one 'long day' turned out to be one of its best.",
    map: [
      { label: "Ingonish", lat: 46.68, lon: -60.39 },
      { label: "Masstown", lat: 45.4, lon: -63.44 },
      { label: "Annapolis Royal", lat: 44.74, lon: -65.51 },
      { label: "Yarmouth", lat: 43.84, lon: -66.12 },
    ],
  },
  {
    n: "11",
    date: "Monday · August 17, 2026",
    region: "The ocean road home",
    leg: "Yarmouth, NS → (ferry) → Bar Harbor, Maine",
    title: "Home by a different sea",
    subtitle: "A crossing of the Gulf of Maine — the elegant way back, no border line, no long drive west.",
    photo: NS_PHOTOS.ferry,
    morningLocation: "Yarmouth — a calm morning; car-ferry check-in is simple and unhurried. (The CAT doesn't sail Tuesdays — today, a Monday, it runs.)",
    breakfast: "A Yarmouth café before boarding, then a second coffee on the open deck once you've cast off.",
    drive: "Barely any on land — today's 'drive' is the ≈ 3 hr 30 min sea crossing on [The CAT](https://www.ferries.ca/) (Yarmouth → Bar Harbor), then a short roll into town.",
    stops: [
      { name: "The Gulf of Maine crossing", time: "3.5 hr", note: "Open water on a fast catamaran — watch for whales, porpoises, and shearwaters while Nova Scotia sinks quietly astern. This is the day's main event, and it's a good one." },
      { name: "[Acadia National Park](https://www.nps.gov/acad/)[[dir|Acadia National Park, Maine]] — Park Loop", time: "2 hr", note: "If timing allows: Sand Beach, Thunder Hole, and the drive up Cadillac Mountain — the first ground the U.S. sees the sunrise on in winter, a neat bookend to Cape Spear's fame." },
    ],
    lunch: "Aboard [The CAT](https://www.ferries.ca/), or a late lobster on the Bar Harbor pier once you land.",
    afternoon: "Bar Harbor and [Acadia](https://www.nps.gov/acad/) — the Park Loop Road, the granite coast, and Cadillac Mountain if the light's right.",
    hotel: "Bar Harbor — the [Bar Harbor Inn](https://www.barharborinn.com/)[[dir|Bar Harbor Inn, Bar Harbor, Maine]] on the waterfront, or the [[map|West Street Hotel|West Street Hotel, Bar Harbor, Maine]] with its rooftop view.",
    dinner: "Bar Harbor — [Havana](https://www.havanamaine.com/)[[dir|Havana Restaurant, Bar Harbor, Maine]], or a classic lobster pound; blueberry pie to finish, because Maine.",
    evening: "The harbour and the Porcupine Islands at dusk — home soil again, but still, unmistakably, on holiday.",
    charging: "Supercharge in Ellsworth just before the island on the way in; Bar Harbor has destination charging and the hotel has Level 2.",
    walking: "Easy — a deck, a pier, and exactly as much of Acadia as you feel like.",
    rainy: "The crossing sails rain or shine; Bar Harbor's shops and the Abbe Museum fill an afternoon; Acadia is atmospheric in mist.",
    sky: "An optional last look up: [Acadia](https://www.nps.gov/acad/) is a dark-sky-friendly park, and Cadillac Mountain or the carriage roads on a clear night give a fine northern sky — though you'll have already had the best of it in Cape Breton.",
    memory: "Standing at the stern as Nova Scotia dissolved into the Gulf — crossing an entire ocean just to get home, the most elegant possible last chapter.",
    map: [
      { label: "Yarmouth", lat: 43.84, lon: -66.12 },
      { label: "Bar Harbor", lat: 44.39, lon: -68.2, ferry: true },
      { label: "Acadia", lat: 44.34, lon: -68.25 },
    ],
  },
  {
    n: "12",
    date: "Tuesday · August 18, 2026",
    region: "The closing chapter",
    leg: "Bar Harbor, Maine → Salt Point, New York",
    title: "The long way home, on purpose",
    subtitle: "One more sunrise if you want it, then an easy road south — or split it, and don't rush.",
    photo: NS_PHOTOS.closing,
    morningLocation: "Bar Harbor — an optional Cadillac Mountain sunrise, or simply a slow breakfast and a last harbour walk.",
    breakfast: "[[map|Jordan Pond House|Jordan Pond House, Acadia National Park, Maine]] popovers in [Acadia](https://www.nps.gov/acad/) (a century-old tradition), or [[map|2 Cats|2 Cats, Bar Harbor, Maine]] in town.",
    drive: "≈ 7 hr 30 min · 720 km direct to Salt Point — or split it with a night in Portland and make it two gentle halves. If you'd rather not do it in one, don't.",
    stops: [
      { name: "[[map|Portland, Maine]]", time: "1–1.5 hr", note: "The perfect midpoint break — one last [Eventide](https://www.eventideoysterco.com/)[[dir|Eventide Oyster Co., Portland, Maine]] oyster and an Old Port stroll, or an easy overnight to bookend the trip where it began." },
      { name: "[[map|Portsmouth, New Hampshire]]", time: "30 min", note: "A final harbour stretch as New England hands you back to the interstate." },
    ],
    lunch: "Portland — a last lobster roll, or a browse and a bite in Freeport if you want one more stop.",
    afternoon: "The easy run south through New England; home to Salt Point by evening, or one soft night in Portland and finish tomorrow.",
    hotel: "Home — your own bed; or a final, unhurried night in Portland to close the loop.",
    dinner: "Home, or a last coastal-Maine dinner if you split the drive — no wrong answer.",
    evening: "The driveway at Salt Point, the car ticking as it cools, twelve days of Atlantic behind you.",
    charging: "A fully solved corridor — Superchargers at Ellsworth, Portland, Kennebunk, and Sturbridge. The last day asks nothing of you.",
    walking: "None required — a driving day, kept deliberately humane.",
    rainy: "Nothing outdoors to protect; a rainy drive home is a gentle, unbothered way to land.",
    memory: "Pulling into Salt Point at dusk, already saying 'next year, the other one' — the trip that was supposed to be the easy one, and turned out to be the one you'd keep talking about.",
    map: [
      { label: "Bar Harbor", lat: 44.39, lon: -68.2 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Salt Point", lat: 41.87, lon: -73.8 },
    ],
  },
];

/** Headline numbers for the "trip at a glance" band. */
export const NS_GLANCE: { k: string; v: string }[] = [
  { k: "12", v: "days · Aug 7–18, 2026" },
  { k: "1", v: "ocean crossing home" },
  { k: "6", v: "dark-sky chances" },
  { k: "1", v: "long drive — the rest are short" },
];

/** The three-beat route summary for the map section. */
export const NS_ROUTE_NOTES: { k: string; v: string }[] = [
  { k: "Out", v: "Up the Maine coast and across at Calais — a soft road-crossing into Canada, no ferry to make." },
  { k: "Around", v: "A relaxed loop: Fundy, the Valley, Halifax, the South Shore, and the Cabot Trail — unhurried the whole way." },
  { k: "Home", v: "The Yarmouth ferry across the Gulf of Maine to Bar Harbor — home by a different sea than you left on." },
];
