import type { TripDay } from "@/lib/trip-types";
import { NS_PHOTOS } from "./photos";

/**
 * NOVA SCOTIA — THE JOURNEY, DAY BY DAY
 * -------------------------------------
 * A relaxed 14-day 2026 road trip for Darren & Melissa: north up the Maine
 * coast, a soft road-crossing into Canada, a gentle loop around Nova Scotia to
 * Cape Breton and the Cabot Trail, and home across the Gulf of Maine by ferry.
 *
 * Written to be warmer and easier than the Newfoundland expedition — comfort,
 * specifics, and reassurance for Melissa; scenic drives, hidden gems, food,
 * engineering, photography, and dark skies for Darren. Timings and distances
 * are honest working estimates — verify and book ahead before the trip.
 */

export const NS_DAYS: TripDay[] = [
  {
    n: "01",
    region: "The gentle launch",
    leg: "Salt Point, NY → Portland, Maine",
    title: "North, without the alarm clock",
    subtitle: "No ferry to catch, no dark start — just the coast of Maine by dinner.",
    photo: NS_PHOTOS.portland,
    morningLocation: "Home in Salt Point, at a civilized hour — coffee on the porch, the car already packed.",
    breakfast: "Something quick at home, or a pastry from the village. The real eating starts tonight.",
    drive: "≈ 5 hr 15 min · 500 km — Taconic to the Mass Pike, then I-95 to the Maine coast. All highway, all easy.",
    stops: [
      { name: "Portsmouth, New Hampshire", time: "45 min", note: "A stretch and a harbour walk where New England first smells like the sea. Coffee in the old brick downtown." },
      { name: "Portland Head Light, Cape Elizabeth", time: "45 min", note: "The most photographed lighthouse in Maine, on your way into town — a soft first postcard for Darren's camera." },
    ],
    lunch: "On the road — a lobster roll in Portsmouth, or hold out for oysters in Portland.",
    afternoon: "Into Portland's Old Port — cobblestones, chandleries, the Eastern Promenade path along Casco Bay.",
    hotel: "The Press Hotel (Autograph Collection) or the Portland Harbor Hotel — walkable to everything, quietly design-forward.",
    dinner: "Eventide Oyster Co. for the brown-butter lobster bun and cold local oysters; Fore Street if you want a proper room and a wood fire.",
    evening: "A slow walk along the working waterfront; the light on Casco Bay, boats coming in.",
    charging: "Superchargers all down the I-95 corridor (Sturbridge, Auburn) and several in Portland itself — charge over dinner, Level 2 at the hotel overnight. Nothing to plan.",
    walking: "Easy — town strolls only.",
    rainy: "Portland Museum of Art (Homer and the Wyeths) or the covered Public Market. A rainy first evening is no loss here.",
    memory: "The first oysters and a lobster roll with the Atlantic finally in the frame — and not one thing about the day that felt hard.",
    map: [
      { label: "Salt Point", lat: 41.87, lon: -73.8 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
    ],
  },
  {
    n: "02",
    region: "Into Canada, softly",
    leg: "Portland, Maine → St. Andrews by-the-Sea, New Brunswick",
    title: "The border you barely feel",
    subtitle: "Up the Maine coast, across at Calais, into the gentlest town in Canada.",
    photo: NS_PHOTOS.standrews,
    morningLocation: "Portland — an unhurried breakfast and one more look at the harbour before you point the car northeast.",
    breakfast: "Standard Baking Co. pastries, or the hotel. Grab a coffee for the coast road.",
    drive: "≈ 4 hr 45 min · 400 km — US-1 up the Bold Coast, over the border at Calais / St. Stephen. The road empties and slows the whole way.",
    stops: [
      { name: "Wiscasset, Maine", time: "45 min", note: "The lobster-roll pilgrimage — Red's Eats or Sprague's, eaten at a picnic table by the river." },
      { name: "St. Stephen, New Brunswick", time: "45 min", note: "The Ganong chocolate town, right at the border — the Chocolate Museum and a bag of chicken-bone candy for the road." },
    ],
    lunch: "Wiscasset — the classic Maine lobster roll, hot butter or cold mayo, your call.",
    afternoon: "Cross into Canada (passports ready; the crossing here is calm and quick), then the short hop to St. Andrews — Kingsbrae Garden or the long wharf on Passamaquoddy Bay.",
    hotel: "The Algonquin Resort — a grand seaside Tudor with EV charging; or the intimate Kingsbrae Arms for something smaller.",
    dinner: "Rossmount Inn, one of the Maritimes' best tables, or the Niger Reef Tea House on the water.",
    evening: "Sunset from the wharf; whales sometimes roll through the bay off the point.",
    charging: "Top up in Augusta before the coast road; Canadian charging begins around St. Stephen and Saint John. Level 2 at the Algonquin overnight — arrive relaxed, not hunting for a plug.",
    walking: "Easy — gardens and a flat seaside town.",
    rainy: "Kingsbrae Garden's pavilions, the Ganong Chocolate Museum, or the Huntsman Fundy Discovery Aquarium.",
    sky: "If skies are clear, the wharf gives your first real spread of stars — light pollution thins the moment you leave the I-95 corridor. An easy, optional first look up.",
    memory: "Crossing into Canada and feeling the whole trip downshift — chocolate in hand, whales in the bay, and nowhere you had to be.",
    map: [
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Wiscasset", lat: 44.0, lon: -69.66 },
      { label: "St. Stephen", lat: 45.19, lon: -67.28 },
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
    ],
  },
  {
    n: "03",
    region: "The highest tides on earth",
    leg: "St. Andrews → Hopewell Rocks & Fundy National Park, New Brunswick",
    title: "Walk the floor of the ocean",
    subtitle: "Time the day to the tide, and stand where the sea will be.",
    photo: NS_PHOTOS.hopewell,
    morningLocation: "St. Andrews — a good breakfast, then east along the Fundy shore (check today's low-tide time first; the whole day pivots on it).",
    breakfast: "The Algonquin's dining room, or Honeybeans in town.",
    drive: "≈ 3 hr 15 min · 260 km to Hopewell, plus the Fundy park loop — an easy day of short hops between big views.",
    stops: [
      { name: "Saint John, NB", time: "1 hr", note: "The uptown red-brick core and the Reversing Falls, where the Fundy tide literally runs the river backwards." },
      { name: "Cape Enrage / Fundy National Park", time: "1.5 hr", note: "Cliffs, a working lighthouse, and coastal trails above the widest tidal range on the planet." },
      { name: "Hopewell Rocks", time: "1.5–2 hr", note: "Descend the stairs to the actual sea floor at low tide and walk among tree-topped flowerpot stacks carved by forty vertical feet of tide." },
    ],
    lunch: "Alma — lobster and chowder at the Tides, and a Kelly's sticky bun that's the size of your hand.",
    afternoon: "Hopewell Rocks at low tide, then Cape Enrage's cliffs; the sea floor you walked at noon is under three storeys of water by dusk.",
    hotel: "A Fundy-shore inn near Alma / Hopewell (the Broadleaf, or the Parkland Village Inn), or into Moncton for more choice.",
    dinner: "Fundy scallops and Alma lobster, a local ale, the tide coming in outside the window.",
    evening: "Back to the flats at dusk to watch the water swallow the ground you stood on — the same view, twice, transformed.",
    charging: "Superchargers in Saint John and Moncton, both near food. Alma is remote — arrive with a good charge and top up before the park.",
    walking: "Easy–moderate — stairs down to the ocean floor at Hopewell; flat clifftop paths at Cape Enrage.",
    rainy: "The tide performs in any weather; the Hopewell interpretive centre and Cape Enrage's café keep you dry between shows.",
    sky: "Best chance yet: Fundy National Park is a certified Dark Sky Preserve. If it's clear and you've stayed outside Moncton, this is the trip's first great dark sky — the Milky Way over the bay, no city glow.",
    memory: "Standing on the ocean floor at noon, then watching four storeys of tide quietly erase it by dark.",
    map: [
      { label: "St. Andrews", lat: 45.07, lon: -67.05 },
      { label: "Saint John", lat: 45.27, lon: -66.06 },
      { label: "Fundy NP", lat: 45.6, lon: -64.95 },
      { label: "Hopewell Rocks", lat: 45.82, lon: -64.58 },
      { label: "Alma", lat: 45.6, lon: -64.95 },
    ],
  },
  {
    n: "04",
    region: "Across into Nova Scotia",
    leg: "Fundy, NB → Wolfville & Grand-Pré → Halifax, Nova Scotia",
    title: "Wine country by the world's biggest tide",
    subtitle: "Cross into Nova Scotia through orchards and dykelands; arrive in Halifax by dark.",
    photo: NS_PHOTOS.wolfville,
    morningLocation: "The Fundy shore — a slow start; the drive into Nova Scotia over the Tantramar marshes is flat and painless.",
    breakfast: "The inn, or a last Alma sticky bun for the road.",
    drive: "≈ 3 hr to Wolfville, then 1 hr on to Halifax · 330 km total — over the isthmus at Amherst into Nova Scotia.",
    stops: [
      { name: "Grand-Pré National Historic Site", time: "1 hr", note: "A UNESCO landscape of Acadian dykelands and the moving story of the 1755 deportation — quiet, beautiful, and grounding." },
      { name: "Wolfville wineries", time: "1.5–2 hr", note: "Lightfoot & Wolfville or Domaine de Grand Pré — Nova Scotia's crisp Tidal Bay whites, tasted on a patio above the flats." },
    ],
    lunch: "Le Caveau at Domaine de Grand Pré, or the Lightfoot & Wolfville terrace — valley-to-table with the Bay of Fundy shining below.",
    afternoon: "Walk the Grand-Pré dykelands, then the genuinely easy hour into Halifax — the biggest city of the trip arrives gently.",
    hotel: "Halifax — the Muir (Autograph Collection) right on the waterfront, or the classic Halliburton in the old town.",
    dinner: "The Bicycle Thief or Drift on the boardwalk; Bar Kismet if you want the local chefs' favourite.",
    evening: "The Halifax waterfront after dark — schooners, buskers, harbour lights, and the longest downtown boardwalk in the world underfoot.",
    charging: "Supercharge in Truro at the midpoint and at several Halifax locations; Level 2 at the hotel overnight.",
    walking: "Easy — vineyard rows and a flat historic site.",
    rainy: "Tastings are indoors; Grand-Pré's interpretive centre is excellent; and Halifax is a city built for a rainy evening.",
    memory: "A glass of Tidal Bay on a vineyard patio, the Bay of Fundy shining below — the moment Nova Scotia stopped being a plan and started being the trip.",
    map: [
      { label: "Alma", lat: 45.6, lon: -64.95 },
      { label: "Amherst", lat: 45.83, lon: -64.21 },
      { label: "Wolfville", lat: 45.09, lon: -64.36 },
      { label: "Halifax", lat: 44.65, lon: -63.57 },
    ],
  },
  {
    n: "05",
    region: "Halifax, at ease",
    leg: "Halifax — a day out of the car",
    title: "A city that feels like a coastal town",
    subtitle: "Waterfront, Citadel, a museum with a Titanic story — and no driving at all.",
    photo: NS_PHOTOS.halifax,
    morningLocation: "Halifax — coffee on the waterfront; today the car doesn't move and neither do you, faster than you want to.",
    breakfast: "The Seaport Farmers' Market (North America's oldest) for coffee and pastries among the stalls.",
    drive: "None to speak of — this is the day that proves the trip isn't all windshield.",
    stops: [
      { name: "Halifax Citadel", time: "1.5 hr", note: "The star-shaped hilltop fort, the noon gun, kilted guards, and the whole harbour laid out below." },
      { name: "Maritime Museum of the Atlantic", time: "1.5 hr", note: "The definitive Titanic collection and the story of the 1917 Halifax Explosion — history and engineering in one waterfront hall for Darren." },
      { name: "Halifax Public Gardens", time: "45 min", note: "Formal Victorian gardens, a bandstand, and a bench in the shade — the softest possible city stop." },
    ],
    lunch: "A lobster roll on the boardwalk, or the Battered Fish; keep it light and outdoors.",
    afternoon: "Take the Dartmouth ferry across the harbour and back — the oldest saltwater ferry in North America and, at a few dollars, the best harbour cruise there is.",
    hotel: "Same Halifax hotel — no repacking, no logistics, just a second easy night.",
    dinner: "Bar Kismet (a seafood tasting), Lot Six, or the Stubborn Goat gastropub — then live East Coast fiddle at The Carleton.",
    evening: "A pint and a tune at The Carleton or the Lower Deck — the real Maritime warmth, no cover charge on the feeling.",
    charging: "The car rests all day on the hotel's Level 2 — genuinely nothing to think about.",
    walking: "Easy — city strolling entirely at your own pace.",
    rainy: "Everything today has a roof — the museums, the market, the brewery, the fiddle. A rainy Halifax day is a good day by design.",
    memory: "The harbour ferry at dusk, the city gold behind you, realizing you hadn't touched the car in a full day and hadn't missed it once.",
    map: [
      { label: "Halifax", lat: 44.65, lon: -63.57 },
      { label: "Dartmouth", lat: 44.67, lon: -63.57 },
    ],
  },
  {
    n: "06",
    region: "The South Shore",
    leg: "Halifax → Peggy's Cove → Mahone Bay → Lunenburg",
    title: "Lighthouses, three churches, and a painted town",
    subtitle: "The classic coast — photographed early, tasted slowly.",
    photo: NS_PHOTOS.peggys,
    morningLocation: "Halifax — an early start out along St. Margarets Bay, ahead of the tour buses, to have Peggy's Cove to yourselves.",
    breakfast: "Grab-and-go from Halifax; a proper brunch waits in Mahone Bay.",
    drive: "≈ 2 hr 30 min total across the whole day · 150 km — short, scenic legs with long stops between.",
    stops: [
      { name: "Peggy's Cove", time: "1–1.5 hr", note: "The red-capped light on wave-worn granite. Go early for the low light, the quiet, and the safe new viewing deck — mind the wet black rock." },
      { name: "Mahone Bay", time: "1 hr", note: "The three steepled churches mirrored in a calm bay, and a main street of makers, bakers, and a very good kouign-amann." },
    ],
    lunch: "Mahone Bay — Oh My Cod or Rebecca's; a pastry and a coffee by the water.",
    afternoon: "Lunenburg's UNESCO Old Town — the boldly painted waterfront, the Fisheries Museum, the Bluenose II if she's in port, and a wander up the coloured streets.",
    hotel: "Lunenburg — the Mecklenburgh Inn or the Lunenburg Arms, right in the old town.",
    dinner: "Lunenburg — the Half Shell for oysters, the Salt Shaker Deli harbourside, or Bar Salvador for something livelier.",
    evening: "The waterfront at blue hour — dories, rigging, and reflections; a nightcap on an inn porch.",
    charging: "Supercharge in Bridgewater (ten minutes from Lunenburg) or back in Halifax; a short-mileage day makes charging an afterthought.",
    walking: "Easy — Peggy's granite is uneven and slick when wet; the towns themselves are flat and gentle.",
    rainy: "The Fisheries Museum of the Atlantic is a superb indoor half-day; Ironworks Distillery for a tasting; and Peggy's Cove is at its most dramatic in fog.",
    sky: "Optional and photogenic rather than dark: if the harbour's clear, the Lunenburg waterfront scatters soft stars over the rigging — not the trip's darkest sky, but its prettiest for a long exposure.",
    memory: "Peggy's Cove almost to yourselves at first light, then a slow lobster supper on the Lunenburg waterfront — the two most photographed places on the coast, both unhurried.",
    map: [
      { label: "Halifax", lat: 44.65, lon: -63.57 },
      { label: "Peggy's Cove", lat: 44.49, lon: -63.92 },
      { label: "Mahone Bay", lat: 44.45, lon: -64.38 },
      { label: "Lunenburg", lat: 44.38, lon: -64.31 },
    ],
  },
  {
    n: "07",
    region: "Toward Cape Breton",
    leg: "Lunenburg → Baddeck, Cape Breton",
    title: "The long, easy reach to the inland sea",
    subtitle: "A scenic repositioning day that ends on the shore of Bras d'Or Lake.",
    photo: NS_PHOTOS.brasdor,
    morningLocation: "Lunenburg — a last harbour coffee, then north; the day is about arriving somewhere serene, not rushing.",
    breakfast: "A Lunenburg café; pastries and a flat white for the road.",
    drive: "≈ 4 hr 30 min · 430 km — up through the province and over the Canso Causeway onto Cape Breton, broken by good stops.",
    stops: [
      { name: "Truro", time: "30 min", note: "A charge and a leg-stretch; if the tide's right, catch the Salmon River tidal bore rolling upstream." },
      { name: "Antigonish", time: "1 hr", note: "A pretty university town for a relaxed main-street lunch — the last real town before the island." },
      { name: "Canso Causeway", time: "15 min", note: "Cross the deepest causeway in the world onto Cape Breton; the road opens and the light changes." },
    ],
    lunch: "Antigonish — a bistro on Main Street; unhurried, good coffee, no rush to the car.",
    afternoon: "Over the causeway and along the shore of Bras d'Or Lake — a vast inland sea — into Baddeck by late afternoon.",
    hotel: "Baddeck — the Inverary Resort on the lake, or the Water's Edge Inn in the village.",
    dinner: "Baddeck — the Bell Buoy, or the community-hall tradition of Baddeck Lobster Suppers (all-you-can-eat mussels and chowder before the lobster).",
    evening: "The Bras d'Or shore at dusk — glass-calm water, loons calling, the quietest night of the trip so far.",
    charging: "Supercharge in Truro and near New Glasgow / Port Hastings on the way; Baddeck has reliable destination charging. Top up here — this is your staging point for the Cabot Trail.",
    walking: "Easy — a stretch-your-legs travel day.",
    rainy: "The drive is the day and it's comfortable in any weather; if it pours, pull tomorrow's Bell museum forward — it's entirely indoors.",
    sky: "Best chance for dark sky tonight: away from the village, the Bras d'Or shore is genuinely dark. If it's clear, step out after dinner — the lake doubles every star.",
    memory: "The first sight of Bras d'Or Lake opening out beyond the causeway — an inland sea you didn't expect, and the calmest water of the whole trip.",
    map: [
      { label: "Lunenburg", lat: 44.38, lon: -64.31 },
      { label: "Truro", lat: 45.37, lon: -63.28 },
      { label: "Antigonish", lat: 45.62, lon: -61.99 },
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
    ],
  },
  {
    n: "08",
    region: "Baddeck & Bras d'Or Lake",
    leg: "Baddeck — a day of invention and calm water",
    title: "Bell's other life",
    subtitle: "The telephone was the least of it. A morning of hydrofoils and flight, an afternoon on the lake.",
    photo: NS_PHOTOS.bellMuseum,
    morningLocation: "Baddeck — an unhurried morning on Bras d'Or; today you barely drive at all.",
    breakfast: "The inn, on the water; a second coffee on the dock.",
    drive: "Almost none — a stay-put day, by design, in the middle of the trip.",
    stops: [
      { name: "Alexander Graham Bell National Historic Site", time: "1.5–2.5 hr", note: "The best small museum on the route. Bell spent his happiest decades on the hill across the bay, and the telephone was only the start: the HD-4 hydrofoil that set a world marine-speed record in 1919; the Silver Dart and the first powered flight in the British Empire; his tetrahedral kites; and a lifetime of work on deafness and communication — all set in a light-filled hall over the lake he chose for exactly this view. Engineering, communication, and beauty in one place." },
    ],
    lunch: "Baddeck — a lakeside lunch; the Bell Buoy's seafood chowder, or a picnic on the government wharf.",
    afternoon: "A Bras d'Or sail on the schooner Amoeba, or a paddle from the shore; or simply a book on the dock and a nap you don't apologize for.",
    hotel: "Same Baddeck inn — no repacking, and a full charge building for tomorrow's Trail.",
    dinner: "Baddeck Lobster Suppers, or a quiet lakefront dinner at the inn as the light goes long.",
    evening: "The dock at dusk; if you sailed, the sunset came to you from the water.",
    charging: "The car sits on Baddeck destination charging all day — bring it to 100% tonight, because the Cabot Trail's chargers are few and far between.",
    walking: "Easy — the museum is flat with lake-view terraces; an optional woodland walk to Uisge Ban Falls if you want to move (moderate, 45 min).",
    rainy: "The Bell museum is entirely indoors and easily fills a slow half-day; the Gaelic College nearby has weaving and piping. A rain day well spent.",
    sky: "Among the best of the whole trip: Bras d'Or Lake, clear and moonless, is superb. If the night cooperates, the inn dock or the museum's own hill gives a wide, dark sky doubled in the water.",
    memory: "Standing under the HD-4's hull and understanding that the man who invented the telephone spent his best years here chasing flight and speed across this lake — and seeing exactly why he chose it.",
    map: [
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
      { label: "Bell Museum", lat: 46.1, lon: -60.74 },
      { label: "Uisge Ban Falls", lat: 46.19, lon: -60.83 },
    ],
  },
  {
    n: "09",
    region: "The Cabot Trail — west",
    leg: "Baddeck → Chéticamp → Cape Breton Highlands (west)",
    title: "The road that everyone means",
    subtitle: "Up the western rampart — switchbacks, the Gulf below, and the Skyline at golden hour.",
    photo: NS_PHOTOS.cabotWest,
    morningLocation: "Baddeck — a full charge and an early, easy start onto the Trail, driving it so the west coast lines up with the afternoon light.",
    breakfast: "Baddeck; a coffee and a breakfast sandwich for the road.",
    drive: "≈ 3 hr of actual driving spread across the whole day · 130 km to Chéticamp plus the Highlands loop — slow, and stopped often.",
    stops: [
      { name: "Margaree Valley", time: "30 min", note: "A gentle salmon-river valley of green hills and old farms — the calm before the coast turns dramatic." },
      { name: "Chéticamp", time: "1 hr", note: "A proud Acadian fishing village — hooked-rug shops, a tall church, and the last full services before the park's west gate." },
      { name: "Skyline Trail", time: "1.5–2 hr", note: "The Trail's signature walk: a wide, mostly flat 7 km loop out to a headland boardwalk that steps down toward the Gulf. Moose are common at dusk. Go for golden hour." },
    ],
    lunch: "Chéticamp — Acadian seafood; a bowl of fish fricot or fresh haddock, with a look at the famous rug hooking.",
    afternoon: "The Skyline Trail for sunset — or, if legs are tired, the drive-up lookoffs at French Mountain and MacKenzie Mountain give ninety percent of the view for none of the walk. Both are the right answer.",
    hotel: "Chéticamp or a Pleasant Bay inn inside the park's reach — small, simple, and perfectly placed for the dark.",
    dinner: "Chéticamp — an Acadian supper; if there's a kitchen party or a fiddle session on, follow the sound.",
    evening: "The Gulf sunset from the western shore, where the sun drops straight into the sea.",
    charging: "This is the one stretch that rewards planning: start from Baddeck at 100%, use Chéticamp's Level 2, and treat the Trail as a loop, not a dash. Think ahead once, and the whole day stays stress-free.",
    walking: "Skyline is easy–moderate — flat and wide but exposed, 7 km round trip; the lookoffs are drive-up. You choose your effort.",
    rainy: "The lookoffs and the drive still deliver in cloud; Chéticamp's Les Trois Pignons rug-hooking museum is a warm hour; save the Skyline for a clear evening.",
    sky: "Best chance for dark sky on the west of the Trail: Cape Breton Highlands has some of the darkest skies in Nova Scotia. If it's clear, the Gulf side after sunset is exceptional — no towns, no glow.",
    memory: "The Skyline headland at golden hour, the boardwalk falling away to the Gulf, a moose in the alders below — the single most cinematic hour of the trip.",
    map: [
      { label: "Baddeck", lat: 46.1, lon: -60.75 },
      { label: "Margaree", lat: 46.34, lon: -61.09 },
      { label: "Chéticamp", lat: 46.63, lon: -61.01 },
      { label: "Skyline Trail", lat: 46.75, lon: -60.86 },
    ],
  },
  {
    n: "10",
    region: "The Cabot Trail — east",
    leg: "Chéticamp → Pleasant Bay → Ingonish, Cape Breton Highlands (east)",
    title: "Down the eastern coast, slowly",
    subtitle: "Beaches instead of cliffs to climb, a warm sea, and the darkest sky of all.",
    photo: NS_PHOTOS.ingonish,
    morningLocation: "The western Highlands — coffee, then up and over the top of the park on the trip's most scenic single stretch.",
    breakfast: "The inn or a Pleasant Bay café before the mountain road.",
    drive: "≈ 2 hr 30 min of actual driving · 110 km — taken all day, because every bend is a lookoff.",
    stops: [
      { name: "Pleasant Bay", time: "30 min – 2 hr", note: "The whale-watching capital of the Trail — pilot whales are near-certain in season; or just the little harbour and a chowder." },
      { name: "Lone Shieling", time: "20 min", note: "A short, flat loop through a rare stand of 350-year-old sugar maples — an easy leg-stretch in deep green quiet." },
      { name: "Neil's Harbour", time: "30 min", note: "A working lighthouse and the Chowder House on the rocks — the best ice-cream-and-a-view stop on the island." },
    ],
    lunch: "Neil's Harbour — the Chowder House by the lighthouse, seafood chowder on a picnic table over the water.",
    afternoon: "Ingonish — the beach (freshwater on one side, warm salt on the other), the easy 4 km Middle Head headland walk, or just the sand. The sea here is genuinely swimmable in late summer.",
    hotel: "The Keltic Lodge at the Highlands, on Middle Head above the sea — the grand resort of the Trail; or a quieter Ingonish inn.",
    dinner: "The Keltic Lodge (the Purple Thistle dining room) or a local seafood shack, sunset over Ingonish Bay.",
    evening: "The Highlands go pitch dark early — tonight is the one to stay up for.",
    charging: "Ingonish has destination charging (the Keltic Lodge and village); bring it to full here before you leave the Trail tomorrow.",
    walking: "Easy — beaches and the flat Middle Head headland; the whale boat does the rest of the work.",
    rainy: "Whale tours still sail in light rain; Neil's Harbour and its ice cream are cozy in fog; and the mountain road is glorious in drifting mist.",
    sky: "The trip's marquee dark sky. Ingonish and the northern Highlands are the best bet of the whole route — if skies are clear, walk down to Ingonish Beach after dark for the Milky Way over the water, no light for miles.",
    memory: "Floating in a warm Ingonish sea in the afternoon, then lying on the same beach after dark under more stars than either of you had ever tried to count.",
    map: [
      { label: "Chéticamp", lat: 46.63, lon: -61.01 },
      { label: "Pleasant Bay", lat: 46.83, lon: -60.8 },
      { label: "Neil's Harbour", lat: 46.81, lon: -60.35 },
      { label: "Ingonish", lat: 46.68, lon: -60.39 },
    ],
  },
  {
    n: "11",
    region: "The long, kind reposition",
    leg: "Ingonish → the Annapolis Valley → Annapolis Royal",
    title: "Home starts turning west",
    subtitle: "The trip's one real drive — broken into a string of small, good reasons to stop.",
    photo: NS_PHOTOS.fundy,
    morningLocation: "Ingonish — an early, unhurried start; the day is long on the map but never grim on the ground.",
    breakfast: "The Keltic Lodge or an Ingonish café; coffee to go and a plan for lunch.",
    drive: "≈ 6 hr moving · 560 km — off the island and down the western side of the province. Deliberately split with stops so it reads as a tour, not a haul.",
    stops: [
      { name: "Whycocomagh / Bras d'Or lookoff", time: "20 min", note: "A last, wide look at the inland sea and a top-up before you leave Cape Breton." },
      { name: "Masstown Market", time: "45 min", note: "A beloved roadside institution near Truro — chowder, fresh bread, a lighthouse, and the best ice cream on the highway." },
      { name: "Annapolis Royal", time: "1 hr", note: "Canada's oldest European settlement, the Historic Gardens, and Fort Anne's grassy earthworks over a tidal basin — a lovely place to land a long day." },
    ],
    lunch: "Masstown Market — chowder and warm bread at a picnic table, then that ice cream for the road.",
    afternoon: "The easy 101 down the Fundy side of the valley to Annapolis Royal; the Historic Gardens and Fort Anne at golden hour.",
    hotel: "Annapolis Royal — the Queen Anne Inn or Hillsdale House, grand heritage inns; or detour to Digby for the Digby Pines and its famous scallops.",
    dinner: "Annapolis Royal — Restaurant Composé or a Main Street bistro; Digby scallops if you've gone that way.",
    evening: "Fort Anne's earthworks at dusk, the tidal Annapolis Basin going pink and silver.",
    charging: "A well-charged, well-fed long day: fast charging along the 104/102/101 at Port Hastings, Truro/Masstown, and New Minas; Level 2 at the inn overnight.",
    walking: "Easy — a market and a garden; the driving is the day's real effort, and it's shared and broken up.",
    rainy: "Masstown is indoor; Annapolis Royal's tidal-power interpretive centre and heritage streets shrug off rain; the drive is comfortable throughout.",
    sky: "A softer, optional sky after the Highlands: the Fundy west shore around Annapolis Royal and Digby Neck is dark. If it's clear, the basin gives a wide, quiet spread of stars.",
    memory: "A market ice cream and a garden stroll mid-drive that turned the trip's one 'long day' into one of its easiest — proof you'd planned it right.",
    map: [
      { label: "Ingonish", lat: 46.68, lon: -60.39 },
      { label: "Whycocomagh", lat: 45.98, lon: -61.13 },
      { label: "Masstown", lat: 45.4, lon: -63.44 },
      { label: "Annapolis Royal", lat: 44.74, lon: -65.51 },
    ],
  },
  {
    n: "12",
    region: "Southwest shore & Yarmouth",
    leg: "Annapolis Royal → the Acadian shore → Yarmouth",
    title: "The last Nova Scotia coast",
    subtitle: "A short, lovely run down the French Shore to the light at Cape Forchu.",
    photo: NS_PHOTOS.capeForchu,
    morningLocation: "Annapolis Royal — a genuinely slow morning; today's drive is short and all coast.",
    breakfast: "The inn, or the Annapolis Royal Farmers' Market (Canada's oldest continuous market) if it's a market day.",
    drive: "≈ 1 hr 45 min · 130 km down Route 1 — the Acadian 'French Shore' — the trip's shortest and most relaxed driving day.",
    stops: [
      { name: "Church Point (Pointe-de-l'Église)", time: "30 min", note: "Église Sainte-Marie, the tallest and largest wooden church in North America — pure Acadian pride, and a quiet stop." },
      { name: "Mavillette Beach", time: "45 min", note: "A wide, warm, dune-backed sand beach — barefoot time and a boardwalk over the marsh." },
      { name: "Cape Forchu Lightstation", time: "1–1.5 hr", note: "The tapered 'apple-core' light on bare rock outside Yarmouth — the trip's last great Atlantic view, with a café in the old keeper's house." },
    ],
    lunch: "The French Shore — Acadian rappie pie (râpure) at a roadside spot, or fresh seafood on the water.",
    afternoon: "Yarmouth's working waterfront and murals, then out to Cape Forchu for the evening light.",
    hotel: "Yarmouth — the Rodd Grand on the harbour; or, for the splurge and the stars, Trout Point Lodge inland (a certified dark-sky destination — see tonight's sky).",
    dinner: "Yarmouth — Rudder's Brew Pub on the harbour, or the Trout Point Lodge dining room if you've gone inland.",
    evening: "Sunset at Cape Forchu — the light, the rocks, the whole Atlantic going gold — the last, best Nova Scotia sundown before the crossing home.",
    charging: "Yarmouth has charging in town; bring the car to full tonight so the drive home after tomorrow's ferry is a straight, solved run.",
    walking: "Easy — a beach, a lighthouse point, and a small-city waterfront.",
    rainy: "The Sweeney Fisheries and Yarmouth County museums; Cape Forchu is moody and wonderful in fog, and the keeper's-house café is warm.",
    sky: "A fine last dark sky: Cape Forchu and the coast southwest of Yarmouth are excellent, and Trout Point Lodge nearby is a certified dark-sky destination. If it's clear, it's Atlantic on one side and stars on the other.",
    memory: "The sun dropping behind the apple-core light at Cape Forchu, bags half-packed and the morning ferry booked — the last and best Nova Scotia sunset.",
    map: [
      { label: "Annapolis Royal", lat: 44.74, lon: -65.51 },
      { label: "Church Point", lat: 44.33, lon: -66.12 },
      { label: "Mavillette", lat: 44.09, lon: -66.16 },
      { label: "Cape Forchu", lat: 43.79, lon: -66.16 },
    ],
  },
  {
    n: "13",
    region: "The ocean road home",
    leg: "Yarmouth, NS → (ferry) → Bar Harbor, Maine",
    title: "Home by a different sea",
    subtitle: "A morning crossing of the Gulf of Maine — the elegant way back, no border line, no long drive west.",
    photo: NS_PHOTOS.ferry,
    morningLocation: "Yarmouth — an early, calm morning; car ferry check-in is simple and unhurried.",
    breakfast: "A Yarmouth café before boarding, then a second coffee on the open deck once you've cast off.",
    drive: "Barely any on land — today's 'drive' is a ≈ 3 hr 30 min sea crossing on The CAT (Yarmouth → Bar Harbor), then a short roll into town.",
    stops: [
      { name: "The Gulf of Maine crossing", time: "3.5 hr", note: "Open water on a fast catamaran — watch for whales, porpoises, and shearwaters while Nova Scotia sinks quietly astern. This is the day's main event, and it's a good one." },
      { name: "Acadia National Park — Park Loop", time: "2 hr", note: "If timing allows: Sand Beach, Thunder Hole, and the drive up Cadillac Mountain — the first ground the U.S. sees the sunrise on in winter, a neat bookend to Cape Spear's fame." },
    ],
    lunch: "Aboard The CAT, or a late lobster on the Bar Harbor pier once you land.",
    afternoon: "Bar Harbor and Acadia — the Park Loop Road, the granite coast, and Cadillac Mountain if the light's right.",
    hotel: "Bar Harbor — the Bar Harbor Inn on the waterfront, or the West Street Hotel with its rooftop view.",
    dinner: "Bar Harbor — Havana, or a classic lobster pound; blueberry pie to finish, because Maine.",
    evening: "The harbour and the Porcupine Islands at dusk — home soil again, but still, unmistakably, on holiday.",
    charging: "Supercharge in Ellsworth just before the island on the way in; Bar Harbor has destination charging and the hotel has Level 2.",
    walking: "Easy — a deck, a pier, and exactly as much of Acadia as you feel like.",
    rainy: "The crossing sails rain or shine; Bar Harbor's shops and the Abbe Museum fill an afternoon; Acadia is atmospheric in mist.",
    sky: "An optional last look up: Acadia is a dark-sky-friendly park, and Cadillac Mountain or the carriage roads on a clear night give a fine northern sky — though you'll have already had the best of it in Cape Breton.",
    memory: "Standing at the stern as Nova Scotia dissolved into the Gulf — crossing an entire ocean just to get home, the most elegant possible last chapter.",
    map: [
      { label: "Yarmouth", lat: 43.84, lon: -66.12 },
      { label: "Bar Harbor", lat: 44.39, lon: -68.2, ferry: true },
      { label: "Acadia", lat: 44.34, lon: -68.25 },
    ],
  },
  {
    n: "14",
    region: "The closing chapter",
    leg: "Bar Harbor, Maine → Salt Point, New York",
    title: "The long way home, on purpose",
    subtitle: "One more sunrise if you want it, then an easy road south — or split it, and don't rush.",
    photo: NS_PHOTOS.closing,
    morningLocation: "Bar Harbor — an optional Cadillac Mountain sunrise, or simply a slow breakfast and a last harbour walk.",
    breakfast: "Jordan Pond House popovers in Acadia (a century-old tradition), or 2 Cats in town.",
    drive: "≈ 7 hr 30 min · 720 km direct to Salt Point — or split it with a night in Portland and make it two gentle halves. If you'd rather not do it in one, don't.",
    stops: [
      { name: "Portland, Maine", time: "1–1.5 hr", note: "The perfect midpoint break — one last Eventide oyster and an Old Port stroll, or an easy overnight to bookend the trip where it began." },
      { name: "Portsmouth, New Hampshire", time: "30 min", note: "A final harbour stretch as New England hands you back to the interstate." },
    ],
    lunch: "Portland — a last lobster roll, or a browse and a bite in Freeport if you want one more stop.",
    afternoon: "The easy run south through New England; home to Salt Point by evening, or one soft night in Portland and finish tomorrow.",
    hotel: "Home — your own bed; or a final, unhurried night in Portland to close the loop.",
    dinner: "Home, or a last coastal-Maine dinner if you split the drive — no wrong answer.",
    evening: "The driveway at Salt Point, the car ticking as it cools, two weeks of Atlantic behind you.",
    charging: "A fully solved corridor — Superchargers at Ellsworth, Portland, Kennebunk, and Sturbridge. The last day asks nothing of you.",
    walking: "None required — a driving day, kept deliberately humane.",
    rainy: "Nothing outdoors to protect; a rainy drive home is a gentle, unbothered way to land.",
    memory: "Pulling into Salt Point at dusk, already saying 'next year, the other one' — the trip that was supposed to be the easy one, and turned out to be the one you'd keep talking about.",
    map: [
      { label: "Bar Harbor", lat: 44.39, lon: -68.2 },
      { label: "Portland", lat: 43.66, lon: -70.26 },
      { label: "Portsmouth", lat: 43.07, lon: -70.76 },
      { label: "Salt Point", lat: 41.87, lon: -73.8 },
    ],
  },
];

/** Headline numbers for the "trip at a glance" band. */
export const NS_GLANCE: { k: string; v: string }[] = [
  { k: "14", v: "days" },
  { k: "1", v: "ocean crossing home" },
  { k: "6", v: "dark-sky nights" },
  { k: "1", v: "long drive — the rest are short" },
];

/** The three-beat route summary for the map section. */
export const NS_ROUTE_NOTES: { k: string; v: string }[] = [
  { k: "Out", v: "Up the Maine coast and across at Calais — a soft road-crossing into Canada, no ferry to make." },
  { k: "Around", v: "A relaxed loop: Fundy, the Valley, Halifax, the South Shore, and the Cabot Trail — unhurried the whole way." },
  { k: "Home", v: "The Yarmouth ferry across the Gulf of Maine to Bar Harbor — home by a different sea than you left on." },
];
